// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct ExtendGlobalTowerArgs {
    pub enemy: String,
    pub team: String,
}

impl Reducer for ExtendGlobalTowerArgs {
    const REDUCER_NAME: &'static str = "extend_global_tower";
}

#[allow(unused)]
pub fn extend_global_tower(enemy: String, team: String) {
    ExtendGlobalTowerArgs { enemy, team }.invoke();
}

#[allow(unused)]
pub fn on_extend_global_tower(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &String, &String) + Send + 'static,
) -> ReducerCallbackId<ExtendGlobalTowerArgs> {
    ExtendGlobalTowerArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let ExtendGlobalTowerArgs { enemy, team } = __args;
        __callback(__identity, __addr, __status, enemy, team);
    })
}

#[allow(unused)]
pub fn once_on_extend_global_tower(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &String, &String) + Send + 'static,
) -> ReducerCallbackId<ExtendGlobalTowerArgs> {
    ExtendGlobalTowerArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let ExtendGlobalTowerArgs { enemy, team } = __args;
        __callback(__identity, __addr, __status, enemy, team);
    })
}

#[allow(unused)]
pub fn remove_on_extend_global_tower(id: ReducerCallbackId<ExtendGlobalTowerArgs>) {
    ExtendGlobalTowerArgs::remove_on_reducer(id);
}
