// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

use super::user_right::UserRight;
#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct GiveRightArgs {
    pub identity: String,
    pub right: UserRight,
}

impl Reducer for GiveRightArgs {
    const REDUCER_NAME: &'static str = "give_right";
}

#[allow(unused)]
pub fn give_right(identity: String, right: UserRight) {
    GiveRightArgs { identity, right }.invoke();
}

#[allow(unused)]
pub fn on_give_right(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &String, &UserRight)
        + Send
        + 'static,
) -> ReducerCallbackId<GiveRightArgs> {
    GiveRightArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let GiveRightArgs { identity, right } = __args;
        __callback(__identity, __addr, __status, identity, right);
    })
}

#[allow(unused)]
pub fn once_on_give_right(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &String, &UserRight) + Send + 'static,
) -> ReducerCallbackId<GiveRightArgs> {
    GiveRightArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let GiveRightArgs { identity, right } = __args;
        __callback(__identity, __addr, __status, identity, right);
    })
}

#[allow(unused)]
pub fn remove_on_give_right(id: ReducerCallbackId<GiveRightArgs>) {
    GiveRightArgs::remove_on_reducer(id);
}
