// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

use super::ladder_status::LadderStatus;
#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct Ladder {
    pub id: u64,
    pub owner: Identity,
    pub creator: Identity,
    pub defeaters: Vec<Identity>,
    pub levels: Vec<String>,
    pub status: LadderStatus,
}

impl TableType for Ladder {
    const TABLE_NAME: &'static str = "Ladder";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for Ladder {
    type PrimaryKey = u64;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.id
    }
}

impl Ladder {
    #[allow(unused)]
    pub fn filter_by_id(id: u64) -> Option<Self> {
        Self::find(|row| row.id == id)
    }
    #[allow(unused)]
    pub fn filter_by_owner(owner: Identity) -> TableIter<Self> {
        Self::filter(|row| row.owner == owner)
    }
    #[allow(unused)]
    pub fn filter_by_creator(creator: Identity) -> TableIter<Self> {
        Self::filter(|row| row.creator == creator)
    }
    #[allow(unused)]
    pub fn filter_by_defeaters(defeaters: Vec<Identity>) -> TableIter<Self> {
        Self::filter(|row| row.defeaters == defeaters)
    }
    #[allow(unused)]
    pub fn filter_by_levels(levels: Vec<String>) -> TableIter<Self> {
        Self::filter(|row| row.levels == levels)
    }
    #[allow(unused)]
    pub fn filter_by_status(status: LadderStatus) -> TableIter<Self> {
        Self::filter(|row| row.status == status)
    }
}
