// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

use super::table_unit::TableUnit;
#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct RunFuseArgs {
    pub a: u64,
    pub b: u64,
    pub unit: TableUnit,
}

impl Reducer for RunFuseArgs {
    const REDUCER_NAME: &'static str = "run_fuse";
}

#[allow(unused)]
pub fn run_fuse(a: u64, b: u64, unit: TableUnit) {
    RunFuseArgs { a, b, unit }.invoke();
}

#[allow(unused)]
pub fn on_run_fuse(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u64, &u64, &TableUnit)
        + Send
        + 'static,
) -> ReducerCallbackId<RunFuseArgs> {
    RunFuseArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let RunFuseArgs { a, b, unit } = __args;
        __callback(__identity, __addr, __status, a, b, unit);
    })
}

#[allow(unused)]
pub fn once_on_run_fuse(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u64, &u64, &TableUnit)
        + Send
        + 'static,
) -> ReducerCallbackId<RunFuseArgs> {
    RunFuseArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let RunFuseArgs { a, b, unit } = __args;
        __callback(__identity, __addr, __status, a, b, unit);
    })
}

#[allow(unused)]
pub fn remove_on_run_fuse(id: ReducerCallbackId<RunFuseArgs>) {
    RunFuseArgs::remove_on_reducer(id);
}
