// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

use super::fused_unit::FusedUnit;
#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct RunState {
    pub id: u64,
    pub user_id: u64,
    pub team: Vec<FusedUnit>,
}

impl TableType for RunState {
    const TABLE_NAME: &'static str = "RunState";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for RunState {
    type PrimaryKey = u64;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.id
    }
}

impl RunState {
    #[allow(unused)]
    pub fn filter_by_id(id: u64) -> Option<Self> {
        Self::find(|row| row.id == id)
    }
    #[allow(unused)]
    pub fn filter_by_user_id(user_id: u64) -> Option<Self> {
        Self::find(|row| row.user_id == user_id)
    }
    #[allow(unused)]
    pub fn filter_by_team(team: Vec<FusedUnit>) -> TableIter<Self> {
        Self::filter(|row| row.team == team)
    }
}
