// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct RunRerollArgs {
    pub force: bool,
}

impl Reducer for RunRerollArgs {
    const REDUCER_NAME: &'static str = "run_reroll";
}

#[allow(unused)]
pub fn run_reroll(force: bool) {
    RunRerollArgs { force }.invoke();
}

#[allow(unused)]
pub fn on_run_reroll(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &bool) + Send + 'static,
) -> ReducerCallbackId<RunRerollArgs> {
    RunRerollArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let RunRerollArgs { force } = __args;
        __callback(__identity, __addr, __status, force);
    })
}

#[allow(unused)]
pub fn once_on_run_reroll(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &bool) + Send + 'static,
) -> ReducerCallbackId<RunRerollArgs> {
    RunRerollArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let RunRerollArgs { force } = __args;
        __callback(__identity, __addr, __status, force);
    })
}

#[allow(unused)]
pub fn remove_on_run_reroll(id: ReducerCallbackId<RunRerollArgs>) {
    RunRerollArgs::remove_on_reducer(id);
}
