// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct SyncTowerLevelsArgs {
    pub tower_id: u64,
    pub levels: Vec<String>,
}

impl Reducer for SyncTowerLevelsArgs {
    const REDUCER_NAME: &'static str = "sync_tower_levels";
}

#[allow(unused)]
pub fn sync_tower_levels(tower_id: u64, levels: Vec<String>) {
    SyncTowerLevelsArgs { tower_id, levels }.invoke();
}

#[allow(unused)]
pub fn on_sync_tower_levels(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u64, &Vec<String>) + Send + 'static,
) -> ReducerCallbackId<SyncTowerLevelsArgs> {
    SyncTowerLevelsArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let SyncTowerLevelsArgs { tower_id, levels } = __args;
        __callback(__identity, __addr, __status, tower_id, levels);
    })
}

#[allow(unused)]
pub fn once_on_sync_tower_levels(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u64, &Vec<String>) + Send + 'static,
) -> ReducerCallbackId<SyncTowerLevelsArgs> {
    SyncTowerLevelsArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let SyncTowerLevelsArgs { tower_id, levels } = __args;
        __callback(__identity, __addr, __status, tower_id, levels);
    })
}

#[allow(unused)]
pub fn remove_on_sync_tower_levels(id: ReducerCallbackId<SyncTowerLevelsArgs>) {
    SyncTowerLevelsArgs::remove_on_reducer(id);
}
