// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

use super::arena_pool::ArenaPool;
#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct UploadPoolArgs {
    pub pool: Vec<ArenaPool>,
}

impl Reducer for UploadPoolArgs {
    const REDUCER_NAME: &'static str = "upload_pool";
}

#[allow(unused)]
pub fn upload_pool(pool: Vec<ArenaPool>) {
    UploadPoolArgs { pool }.invoke();
}

#[allow(unused)]
pub fn on_upload_pool(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &Vec<ArenaPool>) + Send + 'static,
) -> ReducerCallbackId<UploadPoolArgs> {
    UploadPoolArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let UploadPoolArgs { pool } = __args;
        __callback(__identity, __addr, __status, pool);
    })
}

#[allow(unused)]
pub fn once_on_upload_pool(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &Vec<ArenaPool>) + Send + 'static,
) -> ReducerCallbackId<UploadPoolArgs> {
    UploadPoolArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let UploadPoolArgs { pool } = __args;
        __callback(__identity, __addr, __status, pool);
    })
}

#[allow(unused)]
pub fn remove_on_upload_pool(id: ReducerCallbackId<UploadPoolArgs>) {
    UploadPoolArgs::remove_on_reducer(id);
}
