// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminEditNodesArgs {
    pub pack: String,
}

impl From<AdminEditNodesArgs> for super::Reducer {
    fn from(args: AdminEditNodesArgs) -> Self {
        Self::AdminEditNodes { pack: args.pack }
    }
}

impl __sdk::InModule for AdminEditNodesArgs {
    type Module = super::RemoteModule;
}

pub struct AdminEditNodesCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_edit_nodes`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_edit_nodes {
    /// Request that the remote module invoke the reducer `admin_edit_nodes` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_edit_nodes`] callbacks.
    fn admin_edit_nodes(&self, pack: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_edit_nodes`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminEditNodesCallbackId`] can be passed to [`Self::remove_on_admin_edit_nodes`]
    /// to cancel the callback.
    fn on_admin_edit_nodes(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> AdminEditNodesCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_edit_nodes`],
    /// causing it not to run in the future.
    fn remove_on_admin_edit_nodes(&self, callback: AdminEditNodesCallbackId);
}

impl admin_edit_nodes for super::RemoteReducers {
    fn admin_edit_nodes(&self, pack: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("admin_edit_nodes", AdminEditNodesArgs { pack })
    }
    fn on_admin_edit_nodes(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> AdminEditNodesCallbackId {
        AdminEditNodesCallbackId(self.imp.on_reducer(
            "admin_edit_nodes",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AdminEditNodes { pack },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, pack)
            }),
        ))
    }
    fn remove_on_admin_edit_nodes(&self, callback: AdminEditNodesCallbackId) {
        self.imp.remove_on_reducer("admin_edit_nodes", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_edit_nodes`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_edit_nodes {
    /// Set the call-reducer flags for the reducer `admin_edit_nodes` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_edit_nodes(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_edit_nodes for super::SetReducerFlags {
    fn admin_edit_nodes(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("admin_edit_nodes", flags);
    }
}
