// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminEditOwnerArgs {
    pub node_id: u64,
    pub owner_id: u64,
}

impl From<AdminEditOwnerArgs> for super::Reducer {
    fn from(args: AdminEditOwnerArgs) -> Self {
        Self::AdminEditOwner {
            node_id: args.node_id,
            owner_id: args.owner_id,
        }
    }
}

impl __sdk::InModule for AdminEditOwnerArgs {
    type Module = super::RemoteModule;
}

pub struct AdminEditOwnerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_edit_owner`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_edit_owner {
    /// Request that the remote module invoke the reducer `admin_edit_owner` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_edit_owner`] callbacks.
    fn admin_edit_owner(&self, node_id: u64, owner_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_edit_owner`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminEditOwnerCallbackId`] can be passed to [`Self::remove_on_admin_edit_owner`]
    /// to cancel the callback.
    fn on_admin_edit_owner(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &u64) + Send + 'static,
    ) -> AdminEditOwnerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_edit_owner`],
    /// causing it not to run in the future.
    fn remove_on_admin_edit_owner(&self, callback: AdminEditOwnerCallbackId);
}

impl admin_edit_owner for super::RemoteReducers {
    fn admin_edit_owner(&self, node_id: u64, owner_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("admin_edit_owner", AdminEditOwnerArgs { node_id, owner_id })
    }
    fn on_admin_edit_owner(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &u64) + Send + 'static,
    ) -> AdminEditOwnerCallbackId {
        AdminEditOwnerCallbackId(self.imp.on_reducer(
            "admin_edit_owner",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AdminEditOwner { node_id, owner_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, node_id, owner_id)
            }),
        ))
    }
    fn remove_on_admin_edit_owner(&self, callback: AdminEditOwnerCallbackId) {
        self.imp.remove_on_reducer("admin_edit_owner", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_edit_owner`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_edit_owner {
    /// Set the call-reducer flags for the reducer `admin_edit_owner` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_edit_owner(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_edit_owner for super::SetReducerFlags {
    fn admin_edit_owner(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("admin_edit_owner", flags);
    }
}
