// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ContentDeselectLinkArgs {
    pub parent_id: u64,
    pub child_id: u64,
}

impl From<ContentDeselectLinkArgs> for super::Reducer {
    fn from(args: ContentDeselectLinkArgs) -> Self {
        Self::ContentDeselectLink {
            parent_id: args.parent_id,
            child_id: args.child_id,
        }
    }
}

impl __sdk::InModule for ContentDeselectLinkArgs {
    type Module = super::RemoteModule;
}

pub struct ContentDeselectLinkCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `content_deselect_link`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait content_deselect_link {
    /// Request that the remote module invoke the reducer `content_deselect_link` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_content_deselect_link`] callbacks.
    fn content_deselect_link(&self, parent_id: u64, child_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `content_deselect_link`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ContentDeselectLinkCallbackId`] can be passed to [`Self::remove_on_content_deselect_link`]
    /// to cancel the callback.
    fn on_content_deselect_link(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &u64) + Send + 'static,
    ) -> ContentDeselectLinkCallbackId;
    /// Cancel a callback previously registered by [`Self::on_content_deselect_link`],
    /// causing it not to run in the future.
    fn remove_on_content_deselect_link(&self, callback: ContentDeselectLinkCallbackId);
}

impl content_deselect_link for super::RemoteReducers {
    fn content_deselect_link(&self, parent_id: u64, child_id: u64) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "content_deselect_link",
            ContentDeselectLinkArgs {
                parent_id,
                child_id,
            },
        )
    }
    fn on_content_deselect_link(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &u64) + Send + 'static,
    ) -> ContentDeselectLinkCallbackId {
        ContentDeselectLinkCallbackId(self.imp.on_reducer(
            "content_deselect_link",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::ContentDeselectLink {
                                    parent_id,
                                    child_id,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, parent_id, child_id)
            }),
        ))
    }
    fn remove_on_content_deselect_link(&self, callback: ContentDeselectLinkCallbackId) {
        self.imp
            .remove_on_reducer("content_deselect_link", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `content_deselect_link`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_content_deselect_link {
    /// Set the call-reducer flags for the reducer `content_deselect_link` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn content_deselect_link(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_content_deselect_link for super::SetReducerFlags {
    fn content_deselect_link(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("content_deselect_link", flags);
    }
}
