// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ContentVoteLinkArgs {
    pub parent: u64,
    pub child: u64,
    pub vote: bool,
}

impl From<ContentVoteLinkArgs> for super::Reducer {
    fn from(args: ContentVoteLinkArgs) -> Self {
        Self::ContentVoteLink {
            parent: args.parent,
            child: args.child,
            vote: args.vote,
        }
    }
}

impl __sdk::InModule for ContentVoteLinkArgs {
    type Module = super::RemoteModule;
}

pub struct ContentVoteLinkCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `content_vote_link`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait content_vote_link {
    /// Request that the remote module invoke the reducer `content_vote_link` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_content_vote_link`] callbacks.
    fn content_vote_link(&self, parent: u64, child: u64, vote: bool) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `content_vote_link`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ContentVoteLinkCallbackId`] can be passed to [`Self::remove_on_content_vote_link`]
    /// to cancel the callback.
    fn on_content_vote_link(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &u64, &bool) + Send + 'static,
    ) -> ContentVoteLinkCallbackId;
    /// Cancel a callback previously registered by [`Self::on_content_vote_link`],
    /// causing it not to run in the future.
    fn remove_on_content_vote_link(&self, callback: ContentVoteLinkCallbackId);
}

impl content_vote_link for super::RemoteReducers {
    fn content_vote_link(&self, parent: u64, child: u64, vote: bool) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "content_vote_link",
            ContentVoteLinkArgs {
                parent,
                child,
                vote,
            },
        )
    }
    fn on_content_vote_link(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &u64, &bool) + Send + 'static,
    ) -> ContentVoteLinkCallbackId {
        ContentVoteLinkCallbackId(self.imp.on_reducer(
            "content_vote_link",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::ContentVoteLink {
                                    parent,
                                    child,
                                    vote,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, parent, child, vote)
            }),
        ))
    }
    fn remove_on_content_vote_link(&self, callback: ContentVoteLinkCallbackId) {
        self.imp.remove_on_reducer("content_vote_link", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `content_vote_link`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_content_vote_link {
    /// Set the call-reducer flags for the reducer `content_vote_link` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn content_vote_link(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_content_vote_link for super::SetReducerFlags {
    fn content_vote_link(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("content_vote_link", flags);
    }
}
