// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ContentPublishNodeArgs {
    pub pack: String,
    pub parent: Option<u64>,
}

impl From<ContentPublishNodeArgs> for super::Reducer {
    fn from(args: ContentPublishNodeArgs) -> Self {
        Self::ContentPublishNode {
            pack: args.pack,
            parent: args.parent,
        }
    }
}

impl __sdk::InModule for ContentPublishNodeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `content_publish_node`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait content_publish_node {
    /// Request that the remote module invoke the reducer `content_publish_node` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`content_publish_node:content_publish_node_then`] to run a callback after the reducer completes.
    fn content_publish_node(&self, pack: String, parent: Option<u64>) -> __sdk::Result<()> {
        self.content_publish_node_then(pack, parent, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `content_publish_node` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn content_publish_node_then(
        &self,
        pack: String,
        parent: Option<u64>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl content_publish_node for super::RemoteReducers {
    fn content_publish_node_then(
        &self,
        pack: String,
        parent: Option<u64>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ContentPublishNodeArgs { pack, parent }, callback)
    }
}
