// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::t_creation_parts_type::TCreationParts;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `creation_parts`.
///
/// Obtain a handle from the [`CreationPartsTableAccess::creation_parts`] method on [`super::RemoteTables`],
/// like `ctx.db.creation_parts()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.creation_parts().on_insert(...)`.
pub struct CreationPartsTableHandle<'ctx> {
    imp: __sdk::TableHandle<TCreationParts>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `creation_parts`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CreationPartsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CreationPartsTableHandle`], which mediates access to the table `creation_parts`.
    fn creation_parts(&self) -> CreationPartsTableHandle<'_>;
}

impl CreationPartsTableAccess for super::RemoteTables {
    fn creation_parts(&self) -> CreationPartsTableHandle<'_> {
        CreationPartsTableHandle {
            imp: self.imp.get_table::<TCreationParts>("creation_parts"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CreationPartsInsertCallbackId(__sdk::CallbackId);
pub struct CreationPartsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CreationPartsTableHandle<'ctx> {
    type Row = TCreationParts;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TCreationParts> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CreationPartsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CreationPartsInsertCallbackId {
        CreationPartsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CreationPartsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CreationPartsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CreationPartsDeleteCallbackId {
        CreationPartsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CreationPartsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TCreationParts>("creation_parts");
    _table.add_unique_constraint::<u64>("node_id", |row| &row.node_id);
}
pub struct CreationPartsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CreationPartsTableHandle<'ctx> {
    type UpdateCallbackId = CreationPartsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CreationPartsUpdateCallbackId {
        CreationPartsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CreationPartsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TCreationParts>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TCreationParts>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `node_id` unique index on the table `creation_parts`,
/// which allows point queries on the field of the same name
/// via the [`CreationPartsNodeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.creation_parts().node_id().find(...)`.
pub struct CreationPartsNodeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TCreationParts, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CreationPartsTableHandle<'ctx> {
    /// Get a handle on the `node_id` unique index on the table `creation_parts`.
    pub fn node_id(&self) -> CreationPartsNodeIdUnique<'ctx> {
        CreationPartsNodeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("node_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CreationPartsNodeIdUnique<'ctx> {
    /// Find the subscribed row whose `node_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TCreationParts> {
        self.imp.find(col_val)
    }
}
