// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::daily_update_timer_type::DailyUpdateTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `daily_update_timer`.
///
/// Obtain a handle from the [`DailyUpdateTimerTableAccess::daily_update_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.daily_update_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.daily_update_timer().on_insert(...)`.
pub struct DailyUpdateTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<DailyUpdateTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `daily_update_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DailyUpdateTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DailyUpdateTimerTableHandle`], which mediates access to the table `daily_update_timer`.
    fn daily_update_timer(&self) -> DailyUpdateTimerTableHandle<'_>;
}

impl DailyUpdateTimerTableAccess for super::RemoteTables {
    fn daily_update_timer(&self) -> DailyUpdateTimerTableHandle<'_> {
        DailyUpdateTimerTableHandle {
            imp: self.imp.get_table::<DailyUpdateTimer>("daily_update_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DailyUpdateTimerInsertCallbackId(__sdk::CallbackId);
pub struct DailyUpdateTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DailyUpdateTimerTableHandle<'ctx> {
    type Row = DailyUpdateTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DailyUpdateTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DailyUpdateTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DailyUpdateTimerInsertCallbackId {
        DailyUpdateTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DailyUpdateTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DailyUpdateTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DailyUpdateTimerDeleteCallbackId {
        DailyUpdateTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DailyUpdateTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DailyUpdateTimer>("daily_update_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct DailyUpdateTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DailyUpdateTimerTableHandle<'ctx> {
    type UpdateCallbackId = DailyUpdateTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DailyUpdateTimerUpdateCallbackId {
        DailyUpdateTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DailyUpdateTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<DailyUpdateTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DailyUpdateTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `daily_update_timer`,
/// which allows point queries on the field of the same name
/// via the [`DailyUpdateTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.daily_update_timer().scheduled_id().find(...)`.
pub struct DailyUpdateTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DailyUpdateTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DailyUpdateTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `daily_update_timer`.
    pub fn scheduled_id(&self) -> DailyUpdateTimerScheduledIdUnique<'ctx> {
        DailyUpdateTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DailyUpdateTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<DailyUpdateTimer> {
        self.imp.find(col_val)
    }
}
