// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MatchStartFusionArgs {
    pub source_id: u64,
    pub target_id: u64,
}

impl From<MatchStartFusionArgs> for super::Reducer {
    fn from(args: MatchStartFusionArgs) -> Self {
        Self::MatchStartFusion {
            source_id: args.source_id,
            target_id: args.target_id,
        }
    }
}

impl __sdk::InModule for MatchStartFusionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `match_start_fusion`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait match_start_fusion {
    /// Request that the remote module invoke the reducer `match_start_fusion` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`match_start_fusion:match_start_fusion_then`] to run a callback after the reducer completes.
    fn match_start_fusion(&self, source_id: u64, target_id: u64) -> __sdk::Result<()> {
        self.match_start_fusion_then(source_id, target_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `match_start_fusion` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn match_start_fusion_then(
        &self,
        source_id: u64,
        target_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl match_start_fusion for super::RemoteReducers {
    fn match_start_fusion_then(
        &self,
        source_id: u64,
        target_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            MatchStartFusionArgs {
                source_id,
                target_id,
            },
            callback,
        )
    }
}
