// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MatchChooseFusionArgs {
    pub fusion_choice: String,
}

impl From<MatchChooseFusionArgs> for super::Reducer {
    fn from(args: MatchChooseFusionArgs) -> Self {
        Self::MatchChooseFusion {
            fusion_choice: args.fusion_choice,
        }
    }
}

impl __sdk::InModule for MatchChooseFusionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `match_choose_fusion`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait match_choose_fusion {
    /// Request that the remote module invoke the reducer `match_choose_fusion` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`match_choose_fusion:match_choose_fusion_then`] to run a callback after the reducer completes.
    fn match_choose_fusion(&self, fusion_choice: String) -> __sdk::Result<()> {
        self.match_choose_fusion_then(fusion_choice, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `match_choose_fusion` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn match_choose_fusion_then(
        &self,
        fusion_choice: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl match_choose_fusion for super::RemoteReducers {
    fn match_choose_fusion_then(
        &self,
        fusion_choice: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(MatchChooseFusionArgs { fusion_choice }, callback)
    }
}
