// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MatchMoveUnitArgs {
    pub unit_id: u64,
    pub slot_index: i32,
}

impl From<MatchMoveUnitArgs> for super::Reducer {
    fn from(args: MatchMoveUnitArgs) -> Self {
        Self::MatchMoveUnit {
            unit_id: args.unit_id,
            slot_index: args.slot_index,
        }
    }
}

impl __sdk::InModule for MatchMoveUnitArgs {
    type Module = super::RemoteModule;
}

pub struct MatchMoveUnitCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `match_move_unit`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait match_move_unit {
    /// Request that the remote module invoke the reducer `match_move_unit` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_match_move_unit`] callbacks.
    fn match_move_unit(&self, unit_id: u64, slot_index: i32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `match_move_unit`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MatchMoveUnitCallbackId`] can be passed to [`Self::remove_on_match_move_unit`]
    /// to cancel the callback.
    fn on_match_move_unit(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &i32) + Send + 'static,
    ) -> MatchMoveUnitCallbackId;
    /// Cancel a callback previously registered by [`Self::on_match_move_unit`],
    /// causing it not to run in the future.
    fn remove_on_match_move_unit(&self, callback: MatchMoveUnitCallbackId);
}

impl match_move_unit for super::RemoteReducers {
    fn match_move_unit(&self, unit_id: u64, slot_index: i32) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "match_move_unit",
            MatchMoveUnitArgs {
                unit_id,
                slot_index,
            },
        )
    }
    fn on_match_move_unit(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &i32) + Send + 'static,
    ) -> MatchMoveUnitCallbackId {
        MatchMoveUnitCallbackId(self.imp.on_reducer(
            "match_move_unit",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::MatchMoveUnit {
                                    unit_id,
                                    slot_index,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, unit_id, slot_index)
            }),
        ))
    }
    fn remove_on_match_move_unit(&self, callback: MatchMoveUnitCallbackId) {
        self.imp.remove_on_reducer("match_move_unit", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `match_move_unit`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_match_move_unit {
    /// Set the call-reducer flags for the reducer `match_move_unit` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn match_move_unit(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_match_move_unit for super::SetReducerFlags {
    fn match_move_unit(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("match_move_unit", flags);
    }
}
