// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MatchShopBuyArgs {
    pub shop_idx: u8,
}

impl From<MatchShopBuyArgs> for super::Reducer {
    fn from(args: MatchShopBuyArgs) -> Self {
        Self::MatchShopBuy {
            shop_idx: args.shop_idx,
        }
    }
}

impl __sdk::InModule for MatchShopBuyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `match_shop_buy`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait match_shop_buy {
    /// Request that the remote module invoke the reducer `match_shop_buy` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`match_shop_buy:match_shop_buy_then`] to run a callback after the reducer completes.
    fn match_shop_buy(&self, shop_idx: u8) -> __sdk::Result<()> {
        self.match_shop_buy_then(shop_idx, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `match_shop_buy` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn match_shop_buy_then(
        &self,
        shop_idx: u8,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl match_shop_buy for super::RemoteReducers {
    fn match_shop_buy_then(
        &self,
        shop_idx: u8,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(MatchShopBuyArgs { shop_idx }, callback)
    }
}
