// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TBattle {
    pub id: u64,
    pub owner: u64,
    pub ts: u64,
    pub hash: u64,
    pub result: Option<bool>,
    pub left_team_name: String,
    pub right_team_name: String,
    pub left_team: String,
    pub right_team: String,
}

impl __sdk::InModule for TBattle {
    type Module = super::RemoteModule;
}
