// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TVotesHistory {
    pub id: u64,
    pub player_id: u64,
    pub node_id: u64,
    pub is_upvote: bool,
    pub timestamp: u64,
}

impl __sdk::InModule for TVotesHistory {
    type Module = super::RemoteModule;
}
