// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::t_votes_type::TVotes;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `votes`.
///
/// Obtain a handle from the [`VotesTableAccess::votes`] method on [`super::RemoteTables`],
/// like `ctx.db.votes()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.votes().on_insert(...)`.
pub struct VotesTableHandle<'ctx> {
    imp: __sdk::TableHandle<TVotes>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `votes`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VotesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VotesTableHandle`], which mediates access to the table `votes`.
    fn votes(&self) -> VotesTableHandle<'_>;
}

impl VotesTableAccess for super::RemoteTables {
    fn votes(&self) -> VotesTableHandle<'_> {
        VotesTableHandle {
            imp: self.imp.get_table::<TVotes>("votes"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VotesInsertCallbackId(__sdk::CallbackId);
pub struct VotesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VotesTableHandle<'ctx> {
    type Row = TVotes;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TVotes> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VotesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VotesInsertCallbackId {
        VotesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VotesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VotesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VotesDeleteCallbackId {
        VotesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VotesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TVotes>("votes");
    _table.add_unique_constraint::<u64>("player_id", |row| &row.player_id);
}
pub struct VotesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VotesTableHandle<'ctx> {
    type UpdateCallbackId = VotesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VotesUpdateCallbackId {
        VotesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VotesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TVotes>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TVotes>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `player_id` unique index on the table `votes`,
/// which allows point queries on the field of the same name
/// via the [`VotesPlayerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.votes().player_id().find(...)`.
pub struct VotesPlayerIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TVotes, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VotesTableHandle<'ctx> {
    /// Get a handle on the `player_id` unique index on the table `votes`.
    pub fn player_id(&self) -> VotesPlayerIdUnique<'ctx> {
        VotesPlayerIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("player_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VotesPlayerIdUnique<'ctx> {
    /// Find the subscribed row whose `player_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TVotes> {
        self.imp.find(col_val)
    }
}
