// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AdminDailyUpdate {}

impl __sdk::spacetime_module::InModule for AdminDailyUpdate {
    type Module = super::RemoteModule;
}

pub struct AdminDailyUpdateCallbackId(__sdk::callbacks::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_daily_update`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_daily_update {
    /// Request that the remote module invoke the reducer `admin_daily_update` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_daily_update`] callbacks.
    fn admin_daily_update(&self) -> __anyhow::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_daily_update`.
    ///
    /// The [`super::EventContext`] passed to the `callback`
    /// will always have [`__sdk::Event::Reducer`] as its `event`,
    /// but it may or may not have terminated successfully and been committed.
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::EventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminDailyUpdateCallbackId`] can be passed to [`Self::remove_on_admin_daily_update`]
    /// to cancel the callback.
    fn on_admin_daily_update(
        &self,
        callback: impl FnMut(&super::EventContext) + Send + 'static,
    ) -> AdminDailyUpdateCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_daily_update`],
    /// causing it not to run in the future.
    fn remove_on_admin_daily_update(&self, callback: AdminDailyUpdateCallbackId);
}

impl admin_daily_update for super::RemoteReducers {
    fn admin_daily_update(&self) -> __anyhow::Result<()> {
        self.imp
            .call_reducer("admin_daily_update", AdminDailyUpdate {})
    }
    fn on_admin_daily_update(
        &self,
        mut callback: impl FnMut(&super::EventContext) + Send + 'static,
    ) -> AdminDailyUpdateCallbackId {
        AdminDailyUpdateCallbackId(self.imp.on_reducer::<AdminDailyUpdate>(
            "admin_daily_update",
            Box::new(move |ctx: &super::EventContext, args: &AdminDailyUpdate| callback(ctx)),
        ))
    }
    fn remove_on_admin_daily_update(&self, callback: AdminDailyUpdateCallbackId) {
        self.imp
            .remove_on_reducer::<AdminDailyUpdate>("admin_daily_update", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_daily_update`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_daily_update {
    /// Set the call-reducer flags for the reducer `admin_daily_update` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_daily_update(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_daily_update for super::SetReducerFlags {
    fn admin_daily_update(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("admin_daily_update", flags);
    }
}
