// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::game_mode_type::GameMode;
use super::reward_type::Reward;
use super::t_arena_run_archive_type::TArenaRunArchive;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `arena_run_archive`.
///
/// Obtain a handle from the [`ArenaRunArchiveTableAccess::arena_run_archive`] method on [`super::RemoteTables`],
/// like `ctx.db.arena_run_archive()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.arena_run_archive().on_insert(...)`.
pub struct ArenaRunArchiveTableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<TArenaRunArchive>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `arena_run_archive`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ArenaRunArchiveTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ArenaRunArchiveTableHandle`], which mediates access to the table `arena_run_archive`.
    fn arena_run_archive(&self) -> ArenaRunArchiveTableHandle<'_>;
}

impl ArenaRunArchiveTableAccess for super::RemoteTables {
    fn arena_run_archive(&self) -> ArenaRunArchiveTableHandle<'_> {
        ArenaRunArchiveTableHandle {
            imp: self.imp.get_table::<TArenaRunArchive>("arena_run_archive"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ArenaRunArchiveInsertCallbackId(__sdk::callbacks::CallbackId);
pub struct ArenaRunArchiveDeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for ArenaRunArchiveTableHandle<'ctx> {
    type Row = TArenaRunArchive;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TArenaRunArchive> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ArenaRunArchiveInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ArenaRunArchiveInsertCallbackId {
        ArenaRunArchiveInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ArenaRunArchiveInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ArenaRunArchiveDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ArenaRunArchiveDeleteCallbackId {
        ArenaRunArchiveDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ArenaRunArchiveDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ArenaRunArchiveUpdateCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::TableWithPrimaryKey for ArenaRunArchiveTableHandle<'ctx> {
    type UpdateCallbackId = ArenaRunArchiveUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ArenaRunArchiveUpdateCallbackId {
        ArenaRunArchiveUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ArenaRunArchiveUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<TArenaRunArchive>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_with_primary_key::<u64>(
        raw_updates,
        |row: &TArenaRunArchive| &row.id,
    )
    .context("Failed to parse table update for table \"arena_run_archive\"")
}

/// Access to the `id` unique index on the table `arena_run_archive`,
/// which allows point queries on the field of the same name
/// via the [`ArenaRunArchiveIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.arena_run_archive().id().find(...)`.
pub struct ArenaRunArchiveIdUnique<'ctx> {
    imp: __sdk::client_cache::UniqueConstraint<TArenaRunArchive, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ArenaRunArchiveTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `arena_run_archive`.
    pub fn id(&self) -> ArenaRunArchiveIdUnique<'ctx> {
        ArenaRunArchiveIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id", |row| &row.id),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ArenaRunArchiveIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TArenaRunArchive> {
        self.imp.find(col_val)
    }
}
