// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AuctionCancel {
    pub item_id: u64,
}

impl __sdk::spacetime_module::InModule for AuctionCancel {
    type Module = super::RemoteModule;
}

pub struct AuctionCancelCallbackId(__sdk::callbacks::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `auction_cancel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait auction_cancel {
    /// Request that the remote module invoke the reducer `auction_cancel` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_auction_cancel`] callbacks.
    fn auction_cancel(&self, item_id: u64) -> __anyhow::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `auction_cancel`.
    ///
    /// The [`super::EventContext`] passed to the `callback`
    /// will always have [`__sdk::Event::Reducer`] as its `event`,
    /// but it may or may not have terminated successfully and been committed.
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::EventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AuctionCancelCallbackId`] can be passed to [`Self::remove_on_auction_cancel`]
    /// to cancel the callback.
    fn on_auction_cancel(
        &self,
        callback: impl FnMut(&super::EventContext, &u64) + Send + 'static,
    ) -> AuctionCancelCallbackId;
    /// Cancel a callback previously registered by [`Self::on_auction_cancel`],
    /// causing it not to run in the future.
    fn remove_on_auction_cancel(&self, callback: AuctionCancelCallbackId);
}

impl auction_cancel for super::RemoteReducers {
    fn auction_cancel(&self, item_id: u64) -> __anyhow::Result<()> {
        self.imp
            .call_reducer("auction_cancel", AuctionCancel { item_id })
    }
    fn on_auction_cancel(
        &self,
        mut callback: impl FnMut(&super::EventContext, &u64) + Send + 'static,
    ) -> AuctionCancelCallbackId {
        AuctionCancelCallbackId(self.imp.on_reducer::<AuctionCancel>(
            "auction_cancel",
            Box::new(move |ctx: &super::EventContext, args: &AuctionCancel| {
                callback(ctx, &args.item_id)
            }),
        ))
    }
    fn remove_on_auction_cancel(&self, callback: AuctionCancelCallbackId) {
        self.imp
            .remove_on_reducer::<AuctionCancel>("auction_cancel", callback.0)
    }
}
