// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

use super::c_effect_type::CEffect;
use super::c_status_type::CStatus;
use super::c_summon_type::CSummon;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CAbilityDescription {
    pub data: String,
    pub status: Option<CStatus>,
    pub summon: Option<CSummon>,
    pub action: Option<CEffect>,
}

impl __sdk::spacetime_module::InModule for CAbilityDescription {
    type Module = super::RemoteModule;
}
