// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Cleanup {}

impl __sdk::spacetime_module::InModule for Cleanup {
    type Module = super::RemoteModule;
}

pub struct CleanupCallbackId(__sdk::callbacks::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `cleanup`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait cleanup {
    /// Request that the remote module invoke the reducer `cleanup` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_cleanup`] callbacks.
    fn cleanup(&self) -> __anyhow::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `cleanup`.
    ///
    /// The [`super::EventContext`] passed to the `callback`
    /// will always have [`__sdk::Event::Reducer`] as its `event`,
    /// but it may or may not have terminated successfully and been committed.
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::EventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CleanupCallbackId`] can be passed to [`Self::remove_on_cleanup`]
    /// to cancel the callback.
    fn on_cleanup(
        &self,
        callback: impl FnMut(&super::EventContext) + Send + 'static,
    ) -> CleanupCallbackId;
    /// Cancel a callback previously registered by [`Self::on_cleanup`],
    /// causing it not to run in the future.
    fn remove_on_cleanup(&self, callback: CleanupCallbackId);
}

impl cleanup for super::RemoteReducers {
    fn cleanup(&self) -> __anyhow::Result<()> {
        self.imp.call_reducer("cleanup", Cleanup {})
    }
    fn on_cleanup(
        &self,
        mut callback: impl FnMut(&super::EventContext) + Send + 'static,
    ) -> CleanupCallbackId {
        CleanupCallbackId(self.imp.on_reducer::<Cleanup>(
            "cleanup",
            Box::new(move |ctx: &super::EventContext, args: &Cleanup| callback(ctx)),
        ))
    }
    fn remove_on_cleanup(&self, callback: CleanupCallbackId) {
        self.imp.remove_on_reducer::<Cleanup>("cleanup", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `cleanup`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_cleanup {
    /// Set the call-reducer flags for the reducer `cleanup` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn cleanup(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_cleanup for super::SetReducerFlags {
    fn cleanup(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("cleanup", flags);
    }
}
