// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address, ScheduleAt,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct CleanupArgs {}

impl Reducer for CleanupArgs {
    const REDUCER_NAME: &'static str = "cleanup";
}

#[allow(unused)]
pub fn cleanup() {
    CleanupArgs {}.invoke();
}

#[allow(unused)]
pub fn on_cleanup(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status) + Send + 'static,
) -> ReducerCallbackId<CleanupArgs> {
    CleanupArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let CleanupArgs {} = __args;
        __callback(__identity, __addr, __status);
    })
}

#[allow(unused)]
pub fn once_on_cleanup(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status) + Send + 'static,
) -> ReducerCallbackId<CleanupArgs> {
    CleanupArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let CleanupArgs {} = __args;
        __callback(__identity, __addr, __status);
    })
}

#[allow(unused)]
pub fn remove_on_cleanup(id: ReducerCallbackId<CleanupArgs>) {
    CleanupArgs::remove_on_reducer(id);
}
