// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::t_content_vote_type::TContentVote;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `content_vote`.
///
/// Obtain a handle from the [`ContentVoteTableAccess::content_vote`] method on [`super::RemoteTables`],
/// like `ctx.db.content_vote()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.content_vote().on_insert(...)`.
pub struct ContentVoteTableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<TContentVote>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `content_vote`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ContentVoteTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ContentVoteTableHandle`], which mediates access to the table `content_vote`.
    fn content_vote(&self) -> ContentVoteTableHandle<'_>;
}

impl ContentVoteTableAccess for super::RemoteTables {
    fn content_vote(&self) -> ContentVoteTableHandle<'_> {
        ContentVoteTableHandle {
            imp: self.imp.get_table::<TContentVote>("content_vote"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ContentVoteInsertCallbackId(__sdk::callbacks::CallbackId);
pub struct ContentVoteDeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for ContentVoteTableHandle<'ctx> {
    type Row = TContentVote;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TContentVote> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ContentVoteInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContentVoteInsertCallbackId {
        ContentVoteInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ContentVoteInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ContentVoteDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContentVoteDeleteCallbackId {
        ContentVoteDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ContentVoteDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ContentVoteUpdateCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::TableWithPrimaryKey for ContentVoteTableHandle<'ctx> {
    type UpdateCallbackId = ContentVoteUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ContentVoteUpdateCallbackId {
        ContentVoteUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ContentVoteUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<TContentVote>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_with_primary_key::<String>(
        raw_updates,
        |row: &TContentVote| &row.id,
    )
    .context("Failed to parse table update for table \"content_vote\"")
}

/// Access to the `id` unique index on the table `content_vote`,
/// which allows point queries on the field of the same name
/// via the [`ContentVoteIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.content_vote().id().find(...)`.
pub struct ContentVoteIdUnique<'ctx> {
    imp: __sdk::client_cache::UniqueConstraint<TContentVote, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ContentVoteTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `content_vote`.
    pub fn id(&self) -> ContentVoteIdUnique<'ctx> {
        ContentVoteIdUnique {
            imp: self
                .imp
                .get_unique_constraint::<String>("id", |row| &row.id),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ContentVoteIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TContentVote> {
        self.imp.find(col_val)
    }
}
