// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::t_content_favorite_type::TContentFavorite;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `content_favorite`.
///
/// Obtain a handle from the [`ContentFavoriteTableAccess::content_favorite`] method on [`super::RemoteTables`],
/// like `ctx.db.content_favorite()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.content_favorite().on_insert(...)`.
pub struct ContentFavoriteTableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<TContentFavorite>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `content_favorite`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ContentFavoriteTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ContentFavoriteTableHandle`], which mediates access to the table `content_favorite`.
    fn content_favorite(&self) -> ContentFavoriteTableHandle<'_>;
}

impl ContentFavoriteTableAccess for super::RemoteTables {
    fn content_favorite(&self) -> ContentFavoriteTableHandle<'_> {
        ContentFavoriteTableHandle {
            imp: self.imp.get_table::<TContentFavorite>("content_favorite"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ContentFavoriteInsertCallbackId(__sdk::callbacks::CallbackId);
pub struct ContentFavoriteDeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for ContentFavoriteTableHandle<'ctx> {
    type Row = TContentFavorite;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TContentFavorite> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ContentFavoriteInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContentFavoriteInsertCallbackId {
        ContentFavoriteInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ContentFavoriteInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ContentFavoriteDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContentFavoriteDeleteCallbackId {
        ContentFavoriteDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ContentFavoriteDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ContentFavoriteUpdateCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::TableWithPrimaryKey for ContentFavoriteTableHandle<'ctx> {
    type UpdateCallbackId = ContentFavoriteUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ContentFavoriteUpdateCallbackId {
        ContentFavoriteUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ContentFavoriteUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<TContentFavorite>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_with_primary_key::<String>(
        raw_updates,
        |row: &TContentFavorite| &row.owner_type,
    )
    .context("Failed to parse table update for table \"content_favorite\"")
}

/// Access to the `owner_type` unique index on the table `content_favorite`,
/// which allows point queries on the field of the same name
/// via the [`ContentFavoriteOwnerTypeUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.content_favorite().owner_type().find(...)`.
pub struct ContentFavoriteOwnerTypeUnique<'ctx> {
    imp: __sdk::client_cache::UniqueConstraint<TContentFavorite, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ContentFavoriteTableHandle<'ctx> {
    /// Get a handle on the `owner_type` unique index on the table `content_favorite`.
    pub fn owner_type(&self) -> ContentFavoriteOwnerTypeUnique<'ctx> {
        ContentFavoriteOwnerTypeUnique {
            imp: self
                .imp
                .get_unique_constraint::<String>("owner_type", |row| &row.owner_type),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ContentFavoriteOwnerTypeUnique<'ctx> {
    /// Find the subscribed row whose `owner_type` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TContentFavorite> {
        self.imp.find(col_val)
    }
}
