// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::t_daily_state_type::TDailyState;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `daily_state`.
///
/// Obtain a handle from the [`DailyStateTableAccess::daily_state`] method on [`super::RemoteTables`],
/// like `ctx.db.daily_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.daily_state().on_insert(...)`.
pub struct DailyStateTableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<TDailyState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `daily_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DailyStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DailyStateTableHandle`], which mediates access to the table `daily_state`.
    fn daily_state(&self) -> DailyStateTableHandle<'_>;
}

impl DailyStateTableAccess for super::RemoteTables {
    fn daily_state(&self) -> DailyStateTableHandle<'_> {
        DailyStateTableHandle {
            imp: self.imp.get_table::<TDailyState>("daily_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DailyStateInsertCallbackId(__sdk::callbacks::CallbackId);
pub struct DailyStateDeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for DailyStateTableHandle<'ctx> {
    type Row = TDailyState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TDailyState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DailyStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DailyStateInsertCallbackId {
        DailyStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DailyStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DailyStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DailyStateDeleteCallbackId {
        DailyStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DailyStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DailyStateUpdateCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::TableWithPrimaryKey for DailyStateTableHandle<'ctx> {
    type UpdateCallbackId = DailyStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DailyStateUpdateCallbackId {
        DailyStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DailyStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<TDailyState>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_with_primary_key::<u64>(
        raw_updates,
        |row: &TDailyState| &row.owner,
    )
    .context("Failed to parse table update for table \"daily_state\"")
}

/// Access to the `owner` unique index on the table `daily_state`,
/// which allows point queries on the field of the same name
/// via the [`DailyStateOwnerUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.daily_state().owner().find(...)`.
pub struct DailyStateOwnerUnique<'ctx> {
    imp: __sdk::client_cache::UniqueConstraint<TDailyState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DailyStateTableHandle<'ctx> {
    /// Get a handle on the `owner` unique index on the table `daily_state`.
    pub fn owner(&self) -> DailyStateOwnerUnique<'ctx> {
        DailyStateOwnerUnique {
            imp: self
                .imp
                .get_unique_constraint::<u64>("owner", |row| &row.owner),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DailyStateOwnerUnique<'ctx> {
    /// Find the subscribed row whose `owner` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TDailyState> {
        self.imp.find(col_val)
    }
}
