// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::__codegen::{
    self as __sdk, __lib, __sats, __ws,
    anyhow::{self as __anyhow, Context as _},
};

use super::daily_update_timer_type::DailyUpdateTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DailyUpdateReducerArgs {
    pub timer: DailyUpdateTimer,
}

impl From<DailyUpdateReducerArgs> for super::Reducer {
    fn from(args: DailyUpdateReducerArgs) -> Self {
        Self::DailyUpdateReducer { timer: args.timer }
    }
}

impl __sdk::InModule for DailyUpdateReducerArgs {
    type Module = super::RemoteModule;
}

pub struct DailyUpdateReducerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `daily_update_reducer`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait daily_update_reducer {
    /// Request that the remote module invoke the reducer `daily_update_reducer` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_daily_update_reducer`] callbacks.
    fn daily_update_reducer(&self, timer: DailyUpdateTimer) -> __anyhow::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `daily_update_reducer`.
    ///
    /// The [`super::EventContext`] passed to the `callback`
    /// will always have [`__sdk::Event::Reducer`] as its `event`,
    /// but it may or may not have terminated successfully and been committed.
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::EventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DailyUpdateReducerCallbackId`] can be passed to [`Self::remove_on_daily_update_reducer`]
    /// to cancel the callback.
    fn on_daily_update_reducer(
        &self,
        callback: impl FnMut(&super::EventContext, &DailyUpdateTimer) + Send + 'static,
    ) -> DailyUpdateReducerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_daily_update_reducer`],
    /// causing it not to run in the future.
    fn remove_on_daily_update_reducer(&self, callback: DailyUpdateReducerCallbackId);
}

impl daily_update_reducer for super::RemoteReducers {
    fn daily_update_reducer(&self, timer: DailyUpdateTimer) -> __anyhow::Result<()> {
        self.imp
            .call_reducer("daily_update_reducer", DailyUpdateReducerArgs { timer })
    }
    fn on_daily_update_reducer(
        &self,
        mut callback: impl FnMut(&super::EventContext, &DailyUpdateTimer) + Send + 'static,
    ) -> DailyUpdateReducerCallbackId {
        DailyUpdateReducerCallbackId(self.imp.on_reducer(
            "daily_update_reducer",
            Box::new(move |ctx: &super::EventContext| {
                let super::EventContext {
                    event:
                        __sdk::Event::Reducer(__sdk::ReducerEvent {
                            reducer: super::Reducer::DailyUpdateReducer { timer },
                            ..
                        }),
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timer)
            }),
        ))
    }
    fn remove_on_daily_update_reducer(&self, callback: DailyUpdateReducerCallbackId) {
        self.imp
            .remove_on_reducer("daily_update_reducer", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `daily_update_reducer`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_daily_update_reducer {
    /// Set the call-reducer flags for the reducer `daily_update_reducer` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn daily_update_reducer(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_daily_update_reducer for super::SetReducerFlags {
    fn daily_update_reducer(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("daily_update_reducer", flags);
    }
}
