// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FuseChoose {
    pub trigger: i8,
    pub target: i8,
    pub effect: i8,
}

impl __sdk::spacetime_module::InModule for FuseChoose {
    type Module = super::RemoteModule;
}

pub struct FuseChooseCallbackId(__sdk::callbacks::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `fuse_choose`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait fuse_choose {
    /// Request that the remote module invoke the reducer `fuse_choose` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_fuse_choose`] callbacks.
    fn fuse_choose(&self, trigger: i8, target: i8, effect: i8) -> __anyhow::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `fuse_choose`.
    ///
    /// The [`super::EventContext`] passed to the `callback`
    /// will always have [`__sdk::Event::Reducer`] as its `event`,
    /// but it may or may not have terminated successfully and been committed.
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::EventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`FuseChooseCallbackId`] can be passed to [`Self::remove_on_fuse_choose`]
    /// to cancel the callback.
    fn on_fuse_choose(
        &self,
        callback: impl FnMut(&super::EventContext, &i8, &i8, &i8) + Send + 'static,
    ) -> FuseChooseCallbackId;
    /// Cancel a callback previously registered by [`Self::on_fuse_choose`],
    /// causing it not to run in the future.
    fn remove_on_fuse_choose(&self, callback: FuseChooseCallbackId);
}

impl fuse_choose for super::RemoteReducers {
    fn fuse_choose(&self, trigger: i8, target: i8, effect: i8) -> __anyhow::Result<()> {
        self.imp.call_reducer(
            "fuse_choose",
            FuseChoose {
                trigger,
                target,
                effect,
            },
        )
    }
    fn on_fuse_choose(
        &self,
        mut callback: impl FnMut(&super::EventContext, &i8, &i8, &i8) + Send + 'static,
    ) -> FuseChooseCallbackId {
        FuseChooseCallbackId(self.imp.on_reducer::<FuseChoose>(
            "fuse_choose",
            Box::new(move |ctx: &super::EventContext, args: &FuseChoose| {
                callback(ctx, &args.trigger, &args.target, &args.effect)
            }),
        ))
    }
    fn remove_on_fuse_choose(&self, callback: FuseChooseCallbackId) {
        self.imp
            .remove_on_reducer::<FuseChoose>("fuse_choose", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `fuse_choose`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_fuse_choose {
    /// Set the call-reducer flags for the reducer `fuse_choose` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn fuse_choose(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_fuse_choose for super::SetReducerFlags {
    fn fuse_choose(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("fuse_choose", flags);
    }
}
