// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FuseCancel {}

impl __sdk::spacetime_module::InModule for FuseCancel {
    type Module = super::RemoteModule;
}

pub struct FuseCancelCallbackId(__sdk::callbacks::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `fuse_cancel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait fuse_cancel {
    /// Request that the remote module invoke the reducer `fuse_cancel` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_fuse_cancel`] callbacks.
    fn fuse_cancel(&self) -> __anyhow::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `fuse_cancel`.
    ///
    /// The [`super::EventContext`] passed to the `callback`
    /// will always have [`__sdk::Event::Reducer`] as its `event`,
    /// but it may or may not have terminated successfully and been committed.
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::EventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`FuseCancelCallbackId`] can be passed to [`Self::remove_on_fuse_cancel`]
    /// to cancel the callback.
    fn on_fuse_cancel(
        &self,
        callback: impl FnMut(&super::EventContext) + Send + 'static,
    ) -> FuseCancelCallbackId;
    /// Cancel a callback previously registered by [`Self::on_fuse_cancel`],
    /// causing it not to run in the future.
    fn remove_on_fuse_cancel(&self, callback: FuseCancelCallbackId);
}

impl fuse_cancel for super::RemoteReducers {
    fn fuse_cancel(&self) -> __anyhow::Result<()> {
        self.imp.call_reducer("fuse_cancel", FuseCancel {})
    }
    fn on_fuse_cancel(
        &self,
        mut callback: impl FnMut(&super::EventContext) + Send + 'static,
    ) -> FuseCancelCallbackId {
        FuseCancelCallbackId(self.imp.on_reducer::<FuseCancel>(
            "fuse_cancel",
            Box::new(move |ctx: &super::EventContext, args: &FuseCancel| callback(ctx)),
        ))
    }
    fn remove_on_fuse_cancel(&self, callback: FuseCancelCallbackId) {
        self.imp
            .remove_on_reducer::<FuseCancel>("fuse_cancel", callback.0)
    }
}
