// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

use super::fused_unit_type::FusedUnit;
use super::game_mode_type::GameMode;
use super::t_arena_run_type::TArenaRun;
use super::t_auction_type::TAuction;
use super::t_battle_type::TBattle;
use super::t_lootbox_item_type::TLootboxItem;
use super::t_meta_shop_type::TMetaShop;
use super::t_quest_type::TQuest;
use super::t_rainbow_shard_item_type::TRainbowShardItem;
use super::t_unit_item_type::TUnitItem;
use super::t_unit_shard_item_type::TUnitShardItem;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum GlobalEvent {
    LogIn,

    LogOut,

    Register,

    RunStart(GameMode),

    RunFinish(TArenaRun),

    BattleFinish(TBattle),

    MetaShopBuy(TMetaShop),

    GameShopBuy(String),

    GameShopSkip(String),

    GameShopSell(FusedUnit),

    AuctionBuy(TAuction),

    AuctionCancel(TAuction),

    AuctionPost(TAuction),

    ReceiveUnit(TUnitItem),

    DismantleUnit(TUnitItem),

    CraftUnit(TUnitItem),

    ReceiveUnitShard(TUnitShardItem),

    ReceiveRainbowShard(TRainbowShardItem),

    ReceiveLootbox(TLootboxItem),

    OpenLootbox(TLootboxItem),

    QuestAccepted(TQuest),

    QuestComplete(TQuest),

    Fuse(FusedUnit),
}

impl __sdk::spacetime_module::InModule for GlobalEvent {
    type Module = super::RemoteModule;
}
