// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::global_data_type::GlobalData;
use spacetimedb_sdk::__codegen::{
    self as __sdk, __lib, __sats, __ws,
    anyhow::{self as __anyhow, Context as _},
};

/// Table handle for the table `global_data`.
///
/// Obtain a handle from the [`GlobalDataTableAccess::global_data`] method on [`super::RemoteTables`],
/// like `ctx.db.global_data()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.global_data().on_insert(...)`.
pub struct GlobalDataTableHandle<'ctx> {
    imp: __sdk::TableHandle<GlobalData>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `global_data`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GlobalDataTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GlobalDataTableHandle`], which mediates access to the table `global_data`.
    fn global_data(&self) -> GlobalDataTableHandle<'_>;
}

impl GlobalDataTableAccess for super::RemoteTables {
    fn global_data(&self) -> GlobalDataTableHandle<'_> {
        GlobalDataTableHandle {
            imp: self.imp.get_table::<GlobalData>("global_data"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GlobalDataInsertCallbackId(__sdk::CallbackId);
pub struct GlobalDataDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GlobalDataTableHandle<'ctx> {
    type Row = GlobalData;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GlobalData> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GlobalDataInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GlobalDataInsertCallbackId {
        GlobalDataInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GlobalDataInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GlobalDataDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GlobalDataDeleteCallbackId {
        GlobalDataDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GlobalDataDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GlobalData>("global_data");
    _table.add_unique_constraint::<u32>("always_zero", |row| &row.always_zero);
}
#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::TableUpdate<GlobalData>> {
    __sdk::TableUpdate::parse_table_update_no_primary_key(raw_updates)
        .context("Failed to parse table update for table \"global_data\"")
}

/// Access to the `always_zero` unique index on the table `global_data`,
/// which allows point queries on the field of the same name
/// via the [`GlobalDataAlwaysZeroUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.global_data().always_zero().find(...)`.
pub struct GlobalDataAlwaysZeroUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GlobalData, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GlobalDataTableHandle<'ctx> {
    /// Get a handle on the `always_zero` unique index on the table `global_data`.
    pub fn always_zero(&self) -> GlobalDataAlwaysZeroUnique<'ctx> {
        GlobalDataAlwaysZeroUnique {
            imp: self.imp.get_unique_constraint::<u32>("always_zero"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GlobalDataAlwaysZeroUnique<'ctx> {
    /// Find the subscribed row whose `always_zero` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<GlobalData> {
        self.imp.find(col_val)
    }
}
