// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::t_house_type::THouse;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `house`.
///
/// Obtain a handle from the [`HouseTableAccess::house`] method on [`super::RemoteTables`],
/// like `ctx.db.house()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.house().on_insert(...)`.
pub struct HouseTableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<THouse>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `house`.
///
/// Implemented for [`super::RemoteTables`].
pub trait HouseTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`HouseTableHandle`], which mediates access to the table `house`.
    fn house(&self) -> HouseTableHandle<'_>;
}

impl HouseTableAccess for super::RemoteTables {
    fn house(&self) -> HouseTableHandle<'_> {
        HouseTableHandle {
            imp: self.imp.get_table::<THouse>("house"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct HouseInsertCallbackId(__sdk::callbacks::CallbackId);
pub struct HouseDeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for HouseTableHandle<'ctx> {
    type Row = THouse;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = THouse> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = HouseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HouseInsertCallbackId {
        HouseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HouseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = HouseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HouseDeleteCallbackId {
        HouseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HouseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct HouseUpdateCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::TableWithPrimaryKey for HouseTableHandle<'ctx> {
    type UpdateCallbackId = HouseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HouseUpdateCallbackId {
        HouseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HouseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<THouse>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_with_primary_key::<String>(
        raw_updates,
        |row: &THouse| &row.name,
    )
    .context("Failed to parse table update for table \"house\"")
}

/// Access to the `name` unique index on the table `house`,
/// which allows point queries on the field of the same name
/// via the [`HouseNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.house().name().find(...)`.
pub struct HouseNameUnique<'ctx> {
    imp: __sdk::client_cache::UniqueConstraint<THouse, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> HouseTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `house`.
    pub fn name(&self) -> HouseNameUnique<'ctx> {
        HouseNameUnique {
            imp: self
                .imp
                .get_unique_constraint::<String>("name", |row| &row.name),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> HouseNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<THouse> {
        self.imp.find(col_val)
    }
}
