// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address, ScheduleAt,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct IncubatorVoteArgs {
    pub id: u64,
    pub vote: bool,
}

impl Reducer for IncubatorVoteArgs {
    const REDUCER_NAME: &'static str = "incubator_vote";
}

#[allow(unused)]
pub fn incubator_vote(id: u64, vote: bool) {
    IncubatorVoteArgs { id, vote }.invoke();
}

#[allow(unused)]
pub fn on_incubator_vote(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u64, &bool) + Send + 'static,
) -> ReducerCallbackId<IncubatorVoteArgs> {
    IncubatorVoteArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let IncubatorVoteArgs { id, vote } = __args;
        __callback(__identity, __addr, __status, id, vote);
    })
}

#[allow(unused)]
pub fn once_on_incubator_vote(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u64, &bool) + Send + 'static,
) -> ReducerCallbackId<IncubatorVoteArgs> {
    IncubatorVoteArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let IncubatorVoteArgs { id, vote } = __args;
        __callback(__identity, __addr, __status, id, vote);
    })
}

#[allow(unused)]
pub fn remove_on_incubator_vote(id: ReducerCallbackId<IncubatorVoteArgs>) {
    IncubatorVoteArgs::remove_on_reducer(id);
}
