// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct IncubatorPostTrigger {
    pub data: String,
    pub description: String,
}

impl __sdk::spacetime_module::InModule for IncubatorPostTrigger {
    type Module = super::RemoteModule;
}

pub struct IncubatorPostTriggerCallbackId(__sdk::callbacks::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `incubator_post_trigger`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait incubator_post_trigger {
    /// Request that the remote module invoke the reducer `incubator_post_trigger` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_incubator_post_trigger`] callbacks.
    fn incubator_post_trigger(&self, data: String, description: String) -> __anyhow::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `incubator_post_trigger`.
    ///
    /// The [`super::EventContext`] passed to the `callback`
    /// will always have [`__sdk::Event::Reducer`] as its `event`,
    /// but it may or may not have terminated successfully and been committed.
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::EventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`IncubatorPostTriggerCallbackId`] can be passed to [`Self::remove_on_incubator_post_trigger`]
    /// to cancel the callback.
    fn on_incubator_post_trigger(
        &self,
        callback: impl FnMut(&super::EventContext, &String, &String) + Send + 'static,
    ) -> IncubatorPostTriggerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_incubator_post_trigger`],
    /// causing it not to run in the future.
    fn remove_on_incubator_post_trigger(&self, callback: IncubatorPostTriggerCallbackId);
}

impl incubator_post_trigger for super::RemoteReducers {
    fn incubator_post_trigger(&self, data: String, description: String) -> __anyhow::Result<()> {
        self.imp.call_reducer(
            "incubator_post_trigger",
            IncubatorPostTrigger { data, description },
        )
    }
    fn on_incubator_post_trigger(
        &self,
        mut callback: impl FnMut(&super::EventContext, &String, &String) + Send + 'static,
    ) -> IncubatorPostTriggerCallbackId {
        IncubatorPostTriggerCallbackId(self.imp.on_reducer::<IncubatorPostTrigger>(
            "incubator_post_trigger",
            Box::new(
                move |ctx: &super::EventContext, args: &IncubatorPostTrigger| {
                    callback(ctx, &args.data, &args.description)
                },
            ),
        ))
    }
    fn remove_on_incubator_post_trigger(&self, callback: IncubatorPostTriggerCallbackId) {
        self.imp
            .remove_on_reducer::<IncubatorPostTrigger>("incubator_post_trigger", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `incubator_post_trigger`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_incubator_post_trigger {
    /// Set the call-reducer flags for the reducer `incubator_post_trigger` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn incubator_post_trigger(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_incubator_post_trigger for super::SetReducerFlags {
    fn incubator_post_trigger(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("incubator_post_trigger", flags);
    }
}
