// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::t_incubator_unit_representation_type::TIncubatorUnitRepresentation;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `incubator_unit_representation`.
///
/// Obtain a handle from the [`IncubatorUnitRepresentationTableAccess::incubator_unit_representation`] method on [`super::RemoteTables`],
/// like `ctx.db.incubator_unit_representation()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.incubator_unit_representation().on_insert(...)`.
pub struct IncubatorUnitRepresentationTableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<TIncubatorUnitRepresentation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `incubator_unit_representation`.
///
/// Implemented for [`super::RemoteTables`].
pub trait IncubatorUnitRepresentationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`IncubatorUnitRepresentationTableHandle`], which mediates access to the table `incubator_unit_representation`.
    fn incubator_unit_representation(&self) -> IncubatorUnitRepresentationTableHandle<'_>;
}

impl IncubatorUnitRepresentationTableAccess for super::RemoteTables {
    fn incubator_unit_representation(&self) -> IncubatorUnitRepresentationTableHandle<'_> {
        IncubatorUnitRepresentationTableHandle {
            imp: self
                .imp
                .get_table::<TIncubatorUnitRepresentation>("incubator_unit_representation"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct IncubatorUnitRepresentationInsertCallbackId(__sdk::callbacks::CallbackId);
pub struct IncubatorUnitRepresentationDeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for IncubatorUnitRepresentationTableHandle<'ctx> {
    type Row = TIncubatorUnitRepresentation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TIncubatorUnitRepresentation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = IncubatorUnitRepresentationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IncubatorUnitRepresentationInsertCallbackId {
        IncubatorUnitRepresentationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: IncubatorUnitRepresentationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = IncubatorUnitRepresentationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IncubatorUnitRepresentationDeleteCallbackId {
        IncubatorUnitRepresentationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: IncubatorUnitRepresentationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct IncubatorUnitRepresentationUpdateCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::TableWithPrimaryKey for IncubatorUnitRepresentationTableHandle<'ctx> {
    type UpdateCallbackId = IncubatorUnitRepresentationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> IncubatorUnitRepresentationUpdateCallbackId {
        IncubatorUnitRepresentationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: IncubatorUnitRepresentationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<TIncubatorUnitRepresentation>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_with_primary_key::<u64>(
        raw_updates,
        |row: &TIncubatorUnitRepresentation| &row.id,
    )
    .context("Failed to parse table update for table \"incubator_unit_representation\"")
}

/// Access to the `id` unique index on the table `incubator_unit_representation`,
/// which allows point queries on the field of the same name
/// via the [`IncubatorUnitRepresentationIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.incubator_unit_representation().id().find(...)`.
pub struct IncubatorUnitRepresentationIdUnique<'ctx> {
    imp: __sdk::client_cache::UniqueConstraint<TIncubatorUnitRepresentation, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> IncubatorUnitRepresentationTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `incubator_unit_representation`.
    pub fn id(&self) -> IncubatorUnitRepresentationIdUnique<'ctx> {
        IncubatorUnitRepresentationIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id", |row| &row.id),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> IncubatorUnitRepresentationIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TIncubatorUnitRepresentation> {
        self.imp.find(col_val)
    }
}
