// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct IncubatorNewNodeArgs {
    pub kind: String,
    pub data: String,
}

impl From<IncubatorNewNodeArgs> for super::Reducer {
    fn from(args: IncubatorNewNodeArgs) -> Self {
        Self::IncubatorNewNode {
            kind: args.kind,
            data: args.data,
        }
    }
}

impl __sdk::InModule for IncubatorNewNodeArgs {
    type Module = super::RemoteModule;
}

pub struct IncubatorNewNodeCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `incubator_new_node`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait incubator_new_node {
    /// Request that the remote module invoke the reducer `incubator_new_node` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_incubator_new_node`] callbacks.
    fn incubator_new_node(&self, kind: String, data: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `incubator_new_node`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`IncubatorNewNodeCallbackId`] can be passed to [`Self::remove_on_incubator_new_node`]
    /// to cancel the callback.
    fn on_incubator_new_node(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> IncubatorNewNodeCallbackId;
    /// Cancel a callback previously registered by [`Self::on_incubator_new_node`],
    /// causing it not to run in the future.
    fn remove_on_incubator_new_node(&self, callback: IncubatorNewNodeCallbackId);
}

impl incubator_new_node for super::RemoteReducers {
    fn incubator_new_node(&self, kind: String, data: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("incubator_new_node", IncubatorNewNodeArgs { kind, data })
    }
    fn on_incubator_new_node(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> IncubatorNewNodeCallbackId {
        IncubatorNewNodeCallbackId(self.imp.on_reducer(
            "incubator_new_node",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::IncubatorNewNode { kind, data },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, kind, data)
            }),
        ))
    }
    fn remove_on_incubator_new_node(&self, callback: IncubatorNewNodeCallbackId) {
        self.imp.remove_on_reducer("incubator_new_node", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `incubator_new_node`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_incubator_new_node {
    /// Set the call-reducer flags for the reducer `incubator_new_node` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn incubator_new_node(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_incubator_new_node for super::SetReducerFlags {
    fn incubator_new_node(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("incubator_new_node", flags);
    }
}
