// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::t_incubator_trigger_type::TIncubatorTrigger;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `incubator_trigger`.
///
/// Obtain a handle from the [`IncubatorTriggerTableAccess::incubator_trigger`] method on [`super::RemoteTables`],
/// like `ctx.db.incubator_trigger()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.incubator_trigger().on_insert(...)`.
pub struct IncubatorTriggerTableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<TIncubatorTrigger>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `incubator_trigger`.
///
/// Implemented for [`super::RemoteTables`].
pub trait IncubatorTriggerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`IncubatorTriggerTableHandle`], which mediates access to the table `incubator_trigger`.
    fn incubator_trigger(&self) -> IncubatorTriggerTableHandle<'_>;
}

impl IncubatorTriggerTableAccess for super::RemoteTables {
    fn incubator_trigger(&self) -> IncubatorTriggerTableHandle<'_> {
        IncubatorTriggerTableHandle {
            imp: self.imp.get_table::<TIncubatorTrigger>("incubator_trigger"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct IncubatorTriggerInsertCallbackId(__sdk::callbacks::CallbackId);
pub struct IncubatorTriggerDeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for IncubatorTriggerTableHandle<'ctx> {
    type Row = TIncubatorTrigger;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TIncubatorTrigger> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = IncubatorTriggerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IncubatorTriggerInsertCallbackId {
        IncubatorTriggerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: IncubatorTriggerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = IncubatorTriggerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IncubatorTriggerDeleteCallbackId {
        IncubatorTriggerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: IncubatorTriggerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct IncubatorTriggerUpdateCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::TableWithPrimaryKey for IncubatorTriggerTableHandle<'ctx> {
    type UpdateCallbackId = IncubatorTriggerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> IncubatorTriggerUpdateCallbackId {
        IncubatorTriggerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: IncubatorTriggerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<TIncubatorTrigger>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_with_primary_key::<u64>(
        raw_updates,
        |row: &TIncubatorTrigger| &row.id,
    )
    .context("Failed to parse table update for table \"incubator_trigger\"")
}

/// Access to the `id` unique index on the table `incubator_trigger`,
/// which allows point queries on the field of the same name
/// via the [`IncubatorTriggerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.incubator_trigger().id().find(...)`.
pub struct IncubatorTriggerIdUnique<'ctx> {
    imp: __sdk::client_cache::UniqueConstraint<TIncubatorTrigger, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> IncubatorTriggerTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `incubator_trigger`.
    pub fn id(&self) -> IncubatorTriggerIdUnique<'ctx> {
        IncubatorTriggerIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id", |row| &row.id),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> IncubatorTriggerIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TIncubatorTrigger> {
        self.imp.find(col_val)
    }
}
