// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address, ScheduleAt,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct IncubatorDeleteUnitArgs {
    pub id: u64,
}

impl Reducer for IncubatorDeleteUnitArgs {
    const REDUCER_NAME: &'static str = "incubator_delete_unit";
}

#[allow(unused)]
pub fn incubator_delete_unit(id: u64) {
    IncubatorDeleteUnitArgs { id }.invoke();
}

#[allow(unused)]
pub fn on_incubator_delete_unit(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u64) + Send + 'static,
) -> ReducerCallbackId<IncubatorDeleteUnitArgs> {
    IncubatorDeleteUnitArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let IncubatorDeleteUnitArgs { id } = __args;
        __callback(__identity, __addr, __status, id);
    })
}

#[allow(unused)]
pub fn once_on_incubator_delete_unit(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u64) + Send + 'static,
) -> ReducerCallbackId<IncubatorDeleteUnitArgs> {
    IncubatorDeleteUnitArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let IncubatorDeleteUnitArgs { id } = __args;
        __callback(__identity, __addr, __status, id);
    })
}

#[allow(unused)]
pub fn remove_on_incubator_delete_unit(id: ReducerCallbackId<IncubatorDeleteUnitArgs>) {
    IncubatorDeleteUnitArgs::remove_on_reducer(id);
}
