// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address, ScheduleAt,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct LoginArgs {
    pub name: String,
    pub pass: String,
}

impl Reducer for LoginArgs {
    const REDUCER_NAME: &'static str = "login";
}

#[allow(unused)]
pub fn login(name: String, pass: String) {
    LoginArgs { name, pass }.invoke();
}

#[allow(unused)]
pub fn on_login(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &String, &String) + Send + 'static,
) -> ReducerCallbackId<LoginArgs> {
    LoginArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let LoginArgs { name, pass } = __args;
        __callback(__identity, __addr, __status, name, pass);
    })
}

#[allow(unused)]
pub fn once_on_login(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &String, &String) + Send + 'static,
) -> ReducerCallbackId<LoginArgs> {
    LoginArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let LoginArgs { name, pass } = __args;
        __callback(__identity, __addr, __status, name, pass);
    })
}

#[allow(unused)]
pub fn remove_on_login(id: ReducerCallbackId<LoginArgs>) {
    LoginArgs::remove_on_reducer(id);
}
