// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MatchPlayCardArgs {
    pub i: u8,
}

impl From<MatchPlayCardArgs> for super::Reducer {
    fn from(args: MatchPlayCardArgs) -> Self {
        Self::MatchPlayCard { i: args.i }
    }
}

impl __sdk::InModule for MatchPlayCardArgs {
    type Module = super::RemoteModule;
}

pub struct MatchPlayCardCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `match_play_card`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait match_play_card {
    /// Request that the remote module invoke the reducer `match_play_card` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_match_play_card`] callbacks.
    fn match_play_card(&self, i: u8) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `match_play_card`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MatchPlayCardCallbackId`] can be passed to [`Self::remove_on_match_play_card`]
    /// to cancel the callback.
    fn on_match_play_card(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u8) + Send + 'static,
    ) -> MatchPlayCardCallbackId;
    /// Cancel a callback previously registered by [`Self::on_match_play_card`],
    /// causing it not to run in the future.
    fn remove_on_match_play_card(&self, callback: MatchPlayCardCallbackId);
}

impl match_play_card for super::RemoteReducers {
    fn match_play_card(&self, i: u8) -> __sdk::Result<()> {
        self.imp
            .call_reducer("match_play_card", MatchPlayCardArgs { i })
    }
    fn on_match_play_card(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u8) + Send + 'static,
    ) -> MatchPlayCardCallbackId {
        MatchPlayCardCallbackId(self.imp.on_reducer(
            "match_play_card",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::MatchPlayCard { i },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, i)
            }),
        ))
    }
    fn remove_on_match_play_card(&self, callback: MatchPlayCardCallbackId) {
        self.imp.remove_on_reducer("match_play_card", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `match_play_card`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_match_play_card {
    /// Set the call-reducer flags for the reducer `match_play_card` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn match_play_card(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_match_play_card for super::SetReducerFlags {
    fn match_play_card(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("match_play_card", flags);
    }
}
