// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::__codegen::{
    self as __sdk, __lib, __sats, __ws,
    anyhow::{self as __anyhow, Context as _},
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MatchRerollArgs {}

impl From<MatchRerollArgs> for super::Reducer {
    fn from(args: MatchRerollArgs) -> Self {
        Self::MatchReroll
    }
}

impl __sdk::InModule for MatchRerollArgs {
    type Module = super::RemoteModule;
}

pub struct MatchRerollCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `match_reroll`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait match_reroll {
    /// Request that the remote module invoke the reducer `match_reroll` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_match_reroll`] callbacks.
    fn match_reroll(&self) -> __anyhow::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `match_reroll`.
    ///
    /// The [`super::EventContext`] passed to the `callback`
    /// will always have [`__sdk::Event::Reducer`] as its `event`,
    /// but it may or may not have terminated successfully and been committed.
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::EventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MatchRerollCallbackId`] can be passed to [`Self::remove_on_match_reroll`]
    /// to cancel the callback.
    fn on_match_reroll(
        &self,
        callback: impl FnMut(&super::EventContext) + Send + 'static,
    ) -> MatchRerollCallbackId;
    /// Cancel a callback previously registered by [`Self::on_match_reroll`],
    /// causing it not to run in the future.
    fn remove_on_match_reroll(&self, callback: MatchRerollCallbackId);
}

impl match_reroll for super::RemoteReducers {
    fn match_reroll(&self) -> __anyhow::Result<()> {
        self.imp.call_reducer("match_reroll", MatchRerollArgs {})
    }
    fn on_match_reroll(
        &self,
        mut callback: impl FnMut(&super::EventContext) + Send + 'static,
    ) -> MatchRerollCallbackId {
        MatchRerollCallbackId(self.imp.on_reducer(
            "match_reroll",
            Box::new(move |ctx: &super::EventContext| {
                let super::EventContext {
                    event:
                        __sdk::Event::Reducer(__sdk::ReducerEvent {
                            reducer: super::Reducer::MatchReroll {},
                            ..
                        }),
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_match_reroll(&self, callback: MatchRerollCallbackId) {
        self.imp.remove_on_reducer("match_reroll", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `match_reroll`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_match_reroll {
    /// Set the call-reducer flags for the reducer `match_reroll` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn match_reroll(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_match_reroll for super::SetReducerFlags {
    fn match_reroll(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("match_reroll", flags);
    }
}
