// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::game_mode_type::GameMode;
use super::t_player_game_stats_type::TPlayerGameStats;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `player_game_stats`.
///
/// Obtain a handle from the [`PlayerGameStatsTableAccess::player_game_stats`] method on [`super::RemoteTables`],
/// like `ctx.db.player_game_stats()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_game_stats().on_insert(...)`.
pub struct PlayerGameStatsTableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<TPlayerGameStats>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_game_stats`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerGameStatsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerGameStatsTableHandle`], which mediates access to the table `player_game_stats`.
    fn player_game_stats(&self) -> PlayerGameStatsTableHandle<'_>;
}

impl PlayerGameStatsTableAccess for super::RemoteTables {
    fn player_game_stats(&self) -> PlayerGameStatsTableHandle<'_> {
        PlayerGameStatsTableHandle {
            imp: self.imp.get_table::<TPlayerGameStats>("player_game_stats"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerGameStatsInsertCallbackId(__sdk::callbacks::CallbackId);
pub struct PlayerGameStatsDeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for PlayerGameStatsTableHandle<'ctx> {
    type Row = TPlayerGameStats;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TPlayerGameStats> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerGameStatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerGameStatsInsertCallbackId {
        PlayerGameStatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerGameStatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerGameStatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerGameStatsDeleteCallbackId {
        PlayerGameStatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerGameStatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlayerGameStatsUpdateCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::TableWithPrimaryKey for PlayerGameStatsTableHandle<'ctx> {
    type UpdateCallbackId = PlayerGameStatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerGameStatsUpdateCallbackId {
        PlayerGameStatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerGameStatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<TPlayerGameStats>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_with_primary_key::<u64>(
        raw_updates,
        |row: &TPlayerGameStats| &row.id,
    )
    .context("Failed to parse table update for table \"player_game_stats\"")
}

/// Access to the `id` unique index on the table `player_game_stats`,
/// which allows point queries on the field of the same name
/// via the [`PlayerGameStatsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_game_stats().id().find(...)`.
pub struct PlayerGameStatsIdUnique<'ctx> {
    imp: __sdk::client_cache::UniqueConstraint<TPlayerGameStats, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerGameStatsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `player_game_stats`.
    pub fn id(&self) -> PlayerGameStatsIdUnique<'ctx> {
        PlayerGameStatsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id", |row| &row.id),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerGameStatsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TPlayerGameStats> {
        self.imp.find(col_val)
    }
}
