// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::t_player_stats_type::TPlayerStats;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `player_stats`.
///
/// Obtain a handle from the [`PlayerStatsTableAccess::player_stats`] method on [`super::RemoteTables`],
/// like `ctx.db.player_stats()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_stats().on_insert(...)`.
pub struct PlayerStatsTableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<TPlayerStats>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_stats`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerStatsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerStatsTableHandle`], which mediates access to the table `player_stats`.
    fn player_stats(&self) -> PlayerStatsTableHandle<'_>;
}

impl PlayerStatsTableAccess for super::RemoteTables {
    fn player_stats(&self) -> PlayerStatsTableHandle<'_> {
        PlayerStatsTableHandle {
            imp: self.imp.get_table::<TPlayerStats>("player_stats"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerStatsInsertCallbackId(__sdk::callbacks::CallbackId);
pub struct PlayerStatsDeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for PlayerStatsTableHandle<'ctx> {
    type Row = TPlayerStats;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TPlayerStats> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerStatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerStatsInsertCallbackId {
        PlayerStatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerStatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerStatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerStatsDeleteCallbackId {
        PlayerStatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerStatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlayerStatsUpdateCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::TableWithPrimaryKey for PlayerStatsTableHandle<'ctx> {
    type UpdateCallbackId = PlayerStatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerStatsUpdateCallbackId {
        PlayerStatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerStatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<TPlayerStats>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_with_primary_key::<u64>(
        raw_updates,
        |row: &TPlayerStats| &row.id,
    )
    .context("Failed to parse table update for table \"player_stats\"")
}

/// Access to the `id` unique index on the table `player_stats`,
/// which allows point queries on the field of the same name
/// via the [`PlayerStatsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_stats().id().find(...)`.
pub struct PlayerStatsIdUnique<'ctx> {
    imp: __sdk::client_cache::UniqueConstraint<TPlayerStats, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerStatsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `player_stats`.
    pub fn id(&self) -> PlayerStatsIdUnique<'ctx> {
        PlayerStatsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id", |row| &row.id),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerStatsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TPlayerStats> {
        self.imp.find(col_val)
    }
}
