// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct QuestAccept {
    pub id: u64,
}

impl __sdk::spacetime_module::InModule for QuestAccept {
    type Module = super::RemoteModule;
}

pub struct QuestAcceptCallbackId(__sdk::callbacks::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `quest_accept`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait quest_accept {
    /// Request that the remote module invoke the reducer `quest_accept` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_quest_accept`] callbacks.
    fn quest_accept(&self, id: u64) -> __anyhow::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `quest_accept`.
    ///
    /// The [`super::EventContext`] passed to the `callback`
    /// will always have [`__sdk::Event::Reducer`] as its `event`,
    /// but it may or may not have terminated successfully and been committed.
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::EventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`QuestAcceptCallbackId`] can be passed to [`Self::remove_on_quest_accept`]
    /// to cancel the callback.
    fn on_quest_accept(
        &self,
        callback: impl FnMut(&super::EventContext, &u64) + Send + 'static,
    ) -> QuestAcceptCallbackId;
    /// Cancel a callback previously registered by [`Self::on_quest_accept`],
    /// causing it not to run in the future.
    fn remove_on_quest_accept(&self, callback: QuestAcceptCallbackId);
}

impl quest_accept for super::RemoteReducers {
    fn quest_accept(&self, id: u64) -> __anyhow::Result<()> {
        self.imp.call_reducer("quest_accept", QuestAccept { id })
    }
    fn on_quest_accept(
        &self,
        mut callback: impl FnMut(&super::EventContext, &u64) + Send + 'static,
    ) -> QuestAcceptCallbackId {
        QuestAcceptCallbackId(self.imp.on_reducer::<QuestAccept>(
            "quest_accept",
            Box::new(move |ctx: &super::EventContext, args: &QuestAccept| callback(ctx, &args.id)),
        ))
    }
    fn remove_on_quest_accept(&self, callback: QuestAcceptCallbackId) {
        self.imp
            .remove_on_reducer::<QuestAccept>("quest_accept", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `quest_accept`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_quest_accept {
    /// Set the call-reducer flags for the reducer `quest_accept` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn quest_accept(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_quest_accept for super::SetReducerFlags {
    fn quest_accept(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("quest_accept", flags);
    }
}
