// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RewardClaim {
    pub id: u64,
}

impl __sdk::spacetime_module::InModule for RewardClaim {
    type Module = super::RemoteModule;
}

pub struct RewardClaimCallbackId(__sdk::callbacks::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `reward_claim`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait reward_claim {
    /// Request that the remote module invoke the reducer `reward_claim` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_reward_claim`] callbacks.
    fn reward_claim(&self, id: u64) -> __anyhow::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `reward_claim`.
    ///
    /// The [`super::EventContext`] passed to the `callback`
    /// will always have [`__sdk::Event::Reducer`] as its `event`,
    /// but it may or may not have terminated successfully and been committed.
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::EventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RewardClaimCallbackId`] can be passed to [`Self::remove_on_reward_claim`]
    /// to cancel the callback.
    fn on_reward_claim(
        &self,
        callback: impl FnMut(&super::EventContext, &u64) + Send + 'static,
    ) -> RewardClaimCallbackId;
    /// Cancel a callback previously registered by [`Self::on_reward_claim`],
    /// causing it not to run in the future.
    fn remove_on_reward_claim(&self, callback: RewardClaimCallbackId);
}

impl reward_claim for super::RemoteReducers {
    fn reward_claim(&self, id: u64) -> __anyhow::Result<()> {
        self.imp.call_reducer("reward_claim", RewardClaim { id })
    }
    fn on_reward_claim(
        &self,
        mut callback: impl FnMut(&super::EventContext, &u64) + Send + 'static,
    ) -> RewardClaimCallbackId {
        RewardClaimCallbackId(self.imp.on_reducer::<RewardClaim>(
            "reward_claim",
            Box::new(move |ctx: &super::EventContext, args: &RewardClaim| callback(ctx, &args.id)),
        ))
    }
    fn remove_on_reward_claim(&self, callback: RewardClaimCallbackId) {
        self.imp
            .remove_on_reducer::<RewardClaim>("reward_claim", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `reward_claim`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_reward_claim {
    /// Set the call-reducer flags for the reducer `reward_claim` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn reward_claim(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_reward_claim for super::SetReducerFlags {
    fn reward_claim(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("reward_claim", flags);
    }
}
