// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RunStartNormal {}

impl __sdk::spacetime_module::InModule for RunStartNormal {
    type Module = super::RemoteModule;
}

pub struct RunStartNormalCallbackId(__sdk::callbacks::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `run_start_normal`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait run_start_normal {
    /// Request that the remote module invoke the reducer `run_start_normal` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_run_start_normal`] callbacks.
    fn run_start_normal(&self) -> __anyhow::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `run_start_normal`.
    ///
    /// The [`super::EventContext`] passed to the `callback`
    /// will always have [`__sdk::Event::Reducer`] as its `event`,
    /// but it may or may not have terminated successfully and been committed.
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::EventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RunStartNormalCallbackId`] can be passed to [`Self::remove_on_run_start_normal`]
    /// to cancel the callback.
    fn on_run_start_normal(
        &self,
        callback: impl FnMut(&super::EventContext) + Send + 'static,
    ) -> RunStartNormalCallbackId;
    /// Cancel a callback previously registered by [`Self::on_run_start_normal`],
    /// causing it not to run in the future.
    fn remove_on_run_start_normal(&self, callback: RunStartNormalCallbackId);
}

impl run_start_normal for super::RemoteReducers {
    fn run_start_normal(&self) -> __anyhow::Result<()> {
        self.imp.call_reducer("run_start_normal", RunStartNormal {})
    }
    fn on_run_start_normal(
        &self,
        mut callback: impl FnMut(&super::EventContext) + Send + 'static,
    ) -> RunStartNormalCallbackId {
        RunStartNormalCallbackId(self.imp.on_reducer::<RunStartNormal>(
            "run_start_normal",
            Box::new(move |ctx: &super::EventContext, args: &RunStartNormal| callback(ctx)),
        ))
    }
    fn remove_on_run_start_normal(&self, callback: RunStartNormalCallbackId) {
        self.imp
            .remove_on_reducer::<RunStartNormal>("run_start_normal", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `run_start_normal`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_run_start_normal {
    /// Set the call-reducer flags for the reducer `run_start_normal` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn run_start_normal(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_run_start_normal for super::SetReducerFlags {
    fn run_start_normal(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("run_start_normal", flags);
    }
}
