// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SetPassword {
    pub old_pass: String,
    pub new_pass: String,
}

impl __sdk::spacetime_module::InModule for SetPassword {
    type Module = super::RemoteModule;
}

pub struct SetPasswordCallbackId(__sdk::callbacks::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_password`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_password {
    /// Request that the remote module invoke the reducer `set_password` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_password`] callbacks.
    fn set_password(&self, old_pass: String, new_pass: String) -> __anyhow::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_password`.
    ///
    /// The [`super::EventContext`] passed to the `callback`
    /// will always have [`__sdk::Event::Reducer`] as its `event`,
    /// but it may or may not have terminated successfully and been committed.
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::EventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetPasswordCallbackId`] can be passed to [`Self::remove_on_set_password`]
    /// to cancel the callback.
    fn on_set_password(
        &self,
        callback: impl FnMut(&super::EventContext, &String, &String) + Send + 'static,
    ) -> SetPasswordCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_password`],
    /// causing it not to run in the future.
    fn remove_on_set_password(&self, callback: SetPasswordCallbackId);
}

impl set_password for super::RemoteReducers {
    fn set_password(&self, old_pass: String, new_pass: String) -> __anyhow::Result<()> {
        self.imp
            .call_reducer("set_password", SetPassword { old_pass, new_pass })
    }
    fn on_set_password(
        &self,
        mut callback: impl FnMut(&super::EventContext, &String, &String) + Send + 'static,
    ) -> SetPasswordCallbackId {
        SetPasswordCallbackId(self.imp.on_reducer::<SetPassword>(
            "set_password",
            Box::new(move |ctx: &super::EventContext, args: &SetPassword| {
                callback(ctx, &args.old_pass, &args.new_pass)
            }),
        ))
    }
    fn remove_on_set_password(&self, callback: SetPasswordCallbackId) {
        self.imp
            .remove_on_reducer::<SetPassword>("set_password", callback.0)
    }
}
