// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShopSetFreeze {
    pub slot: u8,
    pub value: bool,
}

impl __sdk::spacetime_module::InModule for ShopSetFreeze {
    type Module = super::RemoteModule;
}

pub struct ShopSetFreezeCallbackId(__sdk::callbacks::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `shop_set_freeze`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait shop_set_freeze {
    /// Request that the remote module invoke the reducer `shop_set_freeze` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_shop_set_freeze`] callbacks.
    fn shop_set_freeze(&self, slot: u8, value: bool) -> __anyhow::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `shop_set_freeze`.
    ///
    /// The [`super::EventContext`] passed to the `callback`
    /// will always have [`__sdk::Event::Reducer`] as its `event`,
    /// but it may or may not have terminated successfully and been committed.
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::EventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ShopSetFreezeCallbackId`] can be passed to [`Self::remove_on_shop_set_freeze`]
    /// to cancel the callback.
    fn on_shop_set_freeze(
        &self,
        callback: impl FnMut(&super::EventContext, &u8, &bool) + Send + 'static,
    ) -> ShopSetFreezeCallbackId;
    /// Cancel a callback previously registered by [`Self::on_shop_set_freeze`],
    /// causing it not to run in the future.
    fn remove_on_shop_set_freeze(&self, callback: ShopSetFreezeCallbackId);
}

impl shop_set_freeze for super::RemoteReducers {
    fn shop_set_freeze(&self, slot: u8, value: bool) -> __anyhow::Result<()> {
        self.imp
            .call_reducer("shop_set_freeze", ShopSetFreeze { slot, value })
    }
    fn on_shop_set_freeze(
        &self,
        mut callback: impl FnMut(&super::EventContext, &u8, &bool) + Send + 'static,
    ) -> ShopSetFreezeCallbackId {
        ShopSetFreezeCallbackId(self.imp.on_reducer::<ShopSetFreeze>(
            "shop_set_freeze",
            Box::new(move |ctx: &super::EventContext, args: &ShopSetFreeze| {
                callback(ctx, &args.slot, &args.value)
            }),
        ))
    }
    fn remove_on_shop_set_freeze(&self, callback: ShopSetFreezeCallbackId) {
        self.imp
            .remove_on_reducer::<ShopSetFreeze>("shop_set_freeze", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `shop_set_freeze`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_shop_set_freeze {
    /// Set the call-reducer flags for the reducer `shop_set_freeze` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn shop_set_freeze(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_shop_set_freeze for super::SetReducerFlags {
    fn shop_set_freeze(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("shop_set_freeze", flags);
    }
}
