// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TDailyState {
    pub owner: u64,
    pub ranked_cost: i64,
    pub const_cost: i64,
    pub quests_taken: Vec<u64>,
    pub meta_shop_discount_spent: bool,
}

impl __sdk::spacetime_module::InModule for TDailyState {
    type Module = super::RemoteModule;
}
