// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

use super::lootbox_kind_type::LootboxKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TLootboxItem {
    pub id: u64,
    pub owner: u64,
    pub kind: LootboxKind,
    pub count: u32,
}

impl __sdk::spacetime_module::InModule for TLootboxItem {
    type Module = super::RemoteModule;
}
