// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address, ScheduleAt,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct TPrices {
    pub owner: u64,
    pub ranked_mode: i64,
    pub const_mode: i64,
}

impl TableType for TPrices {
    const TABLE_NAME: &'static str = "TPrices";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for TPrices {
    type PrimaryKey = u64;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.owner
    }
}

impl TPrices {
    #[allow(unused)]
    pub fn filter_by_owner(owner: u64) -> TableIter<Self> {
        Self::filter(|row| row.owner == owner)
    }
    #[allow(unused)]
    pub fn find_by_owner(owner: u64) -> Option<Self> {
        Self::find(|row| row.owner == owner)
    }
    #[allow(unused)]
    pub fn filter_by_ranked_mode(ranked_mode: i64) -> TableIter<Self> {
        Self::filter(|row| row.ranked_mode == ranked_mode)
    }
    #[allow(unused)]
    pub fn filter_by_const_mode(const_mode: i64) -> TableIter<Self> {
        Self::filter(|row| row.const_mode == const_mode)
    }
}
