// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

use super::game_mode_type::GameMode;
use super::quest_variant_type::QuestVariant;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TQuest {
    pub id: u64,
    pub owner: u64,
    pub mode: GameMode,
    pub variant: QuestVariant,
    pub counter: u32,
    pub goal: u32,
    pub reward: i64,
    pub complete: bool,
}

impl __sdk::spacetime_module::InModule for TQuest {
    type Module = super::RemoteModule;
}
