// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct TStatus {
    pub name: String,
    pub description: String,
    pub polarity: i8,
    pub trigger: String,
}

impl TableType for TStatus {
    const TABLE_NAME: &'static str = "TStatus";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for TStatus {
    type PrimaryKey = String;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.name
    }
}

impl TStatus {
    #[allow(unused)]
    pub fn filter_by_name(name: String) -> Option<Self> {
        Self::find(|row| row.name == name)
    }
    #[allow(unused)]
    pub fn filter_by_description(description: String) -> TableIter<Self> {
        Self::filter(|row| row.description == description)
    }
    #[allow(unused)]
    pub fn filter_by_polarity(polarity: i8) -> TableIter<Self> {
        Self::filter(|row| row.polarity == polarity)
    }
    #[allow(unused)]
    pub fn filter_by_trigger(trigger: String) -> TableIter<Self> {
        Self::filter(|row| row.trigger == trigger)
    }
}
