// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address, ScheduleAt,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct TeamSwapUnitsArgs {
    pub team: u64,
    pub from: u8,
    pub to: u8,
}

impl Reducer for TeamSwapUnitsArgs {
    const REDUCER_NAME: &'static str = "team_swap_units";
}

#[allow(unused)]
pub fn team_swap_units(team: u64, from: u8, to: u8) {
    TeamSwapUnitsArgs { team, from, to }.invoke();
}

#[allow(unused)]
pub fn on_team_swap_units(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u64, &u8, &u8) + Send + 'static,
) -> ReducerCallbackId<TeamSwapUnitsArgs> {
    TeamSwapUnitsArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let TeamSwapUnitsArgs { team, from, to } = __args;
        __callback(__identity, __addr, __status, team, from, to);
    })
}

#[allow(unused)]
pub fn once_on_team_swap_units(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u64, &u8, &u8) + Send + 'static,
) -> ReducerCallbackId<TeamSwapUnitsArgs> {
    TeamSwapUnitsArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let TeamSwapUnitsArgs { team, from, to } = __args;
        __callback(__identity, __addr, __status, team, from, to);
    })
}

#[allow(unused)]
pub fn remove_on_team_swap_units(id: ReducerCallbackId<TeamSwapUnitsArgs>) {
    TeamSwapUnitsArgs::remove_on_reducer(id);
}
