// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address, ScheduleAt,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct TeamRenameArgs {
    pub team: u64,
    pub name: String,
}

impl Reducer for TeamRenameArgs {
    const REDUCER_NAME: &'static str = "team_rename";
}

#[allow(unused)]
pub fn team_rename(team: u64, name: String) {
    TeamRenameArgs { team, name }.invoke();
}

#[allow(unused)]
pub fn on_team_rename(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u64, &String) + Send + 'static,
) -> ReducerCallbackId<TeamRenameArgs> {
    TeamRenameArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let TeamRenameArgs { team, name } = __args;
        __callback(__identity, __addr, __status, team, name);
    })
}

#[allow(unused)]
pub fn once_on_team_rename(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u64, &String) + Send + 'static,
) -> ReducerCallbackId<TeamRenameArgs> {
    TeamRenameArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let TeamRenameArgs { team, name } = __args;
        __callback(__identity, __addr, __status, team, name);
    })
}

#[allow(unused)]
pub fn remove_on_team_rename(id: ReducerCallbackId<TeamRenameArgs>) {
    TeamRenameArgs::remove_on_reducer(id);
}
