// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address, ScheduleAt,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct TeamAddUnitArgs {
    pub team: u64,
    pub unit: u64,
}

impl Reducer for TeamAddUnitArgs {
    const REDUCER_NAME: &'static str = "team_add_unit";
}

#[allow(unused)]
pub fn team_add_unit(team: u64, unit: u64) {
    TeamAddUnitArgs { team, unit }.invoke();
}

#[allow(unused)]
pub fn on_team_add_unit(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u64, &u64) + Send + 'static,
) -> ReducerCallbackId<TeamAddUnitArgs> {
    TeamAddUnitArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let TeamAddUnitArgs { team, unit } = __args;
        __callback(__identity, __addr, __status, team, unit);
    })
}

#[allow(unused)]
pub fn once_on_team_add_unit(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u64, &u64) + Send + 'static,
) -> ReducerCallbackId<TeamAddUnitArgs> {
    TeamAddUnitArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let TeamAddUnitArgs { team, unit } = __args;
        __callback(__identity, __addr, __status, team, unit);
    })
}

#[allow(unused)]
pub fn remove_on_team_add_unit(id: ReducerCallbackId<TeamAddUnitArgs>) {
    TeamAddUnitArgs::remove_on_reducer(id);
}
