// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TeamRemoveUnit {
    pub team: u64,
    pub unit: u64,
}

impl __sdk::spacetime_module::InModule for TeamRemoveUnit {
    type Module = super::RemoteModule;
}

pub struct TeamRemoveUnitCallbackId(__sdk::callbacks::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `team_remove_unit`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait team_remove_unit {
    /// Request that the remote module invoke the reducer `team_remove_unit` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_team_remove_unit`] callbacks.
    fn team_remove_unit(&self, team: u64, unit: u64) -> __anyhow::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `team_remove_unit`.
    ///
    /// The [`super::EventContext`] passed to the `callback`
    /// will always have [`__sdk::Event::Reducer`] as its `event`,
    /// but it may or may not have terminated successfully and been committed.
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::EventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`TeamRemoveUnitCallbackId`] can be passed to [`Self::remove_on_team_remove_unit`]
    /// to cancel the callback.
    fn on_team_remove_unit(
        &self,
        callback: impl FnMut(&super::EventContext, &u64, &u64) + Send + 'static,
    ) -> TeamRemoveUnitCallbackId;
    /// Cancel a callback previously registered by [`Self::on_team_remove_unit`],
    /// causing it not to run in the future.
    fn remove_on_team_remove_unit(&self, callback: TeamRemoveUnitCallbackId);
}

impl team_remove_unit for super::RemoteReducers {
    fn team_remove_unit(&self, team: u64, unit: u64) -> __anyhow::Result<()> {
        self.imp
            .call_reducer("team_remove_unit", TeamRemoveUnit { team, unit })
    }
    fn on_team_remove_unit(
        &self,
        mut callback: impl FnMut(&super::EventContext, &u64, &u64) + Send + 'static,
    ) -> TeamRemoveUnitCallbackId {
        TeamRemoveUnitCallbackId(self.imp.on_reducer::<TeamRemoveUnit>(
            "team_remove_unit",
            Box::new(move |ctx: &super::EventContext, args: &TeamRemoveUnit| {
                callback(ctx, &args.team, &args.unit)
            }),
        ))
    }
    fn remove_on_team_remove_unit(&self, callback: TeamRemoveUnitCallbackId) {
        self.imp
            .remove_on_reducer::<TeamRemoveUnit>("team_remove_unit", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `team_remove_unit`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_team_remove_unit {
    /// Set the call-reducer flags for the reducer `team_remove_unit` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn team_remove_unit(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_team_remove_unit for super::SetReducerFlags {
    fn team_remove_unit(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("team_remove_unit", flags);
    }
}
