// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::c_unit_type::CUnit;
use super::t_units_type::TUnits;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `units`.
///
/// Obtain a handle from the [`UnitsTableAccess::units`] method on [`super::RemoteTables`],
/// like `ctx.db.units()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.units().on_insert(...)`.
pub struct UnitsTableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<TUnits>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `units`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UnitsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UnitsTableHandle`], which mediates access to the table `units`.
    fn units(&self) -> UnitsTableHandle<'_>;
}

impl UnitsTableAccess for super::RemoteTables {
    fn units(&self) -> UnitsTableHandle<'_> {
        UnitsTableHandle {
            imp: self.imp.get_table::<TUnits>("units"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UnitsInsertCallbackId(__sdk::callbacks::CallbackId);
pub struct UnitsDeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for UnitsTableHandle<'ctx> {
    type Row = TUnits;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TUnits> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UnitsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UnitsInsertCallbackId {
        UnitsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UnitsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UnitsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UnitsDeleteCallbackId {
        UnitsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UnitsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<TUnits>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_no_primary_key(raw_updates)
        .context("Failed to parse table update for table \"units\"")
}
