// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::t_unit_balance_type::TUnitBalance;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `unit_balance`.
///
/// Obtain a handle from the [`UnitBalanceTableAccess::unit_balance`] method on [`super::RemoteTables`],
/// like `ctx.db.unit_balance()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.unit_balance().on_insert(...)`.
pub struct UnitBalanceTableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<TUnitBalance>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `unit_balance`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UnitBalanceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UnitBalanceTableHandle`], which mediates access to the table `unit_balance`.
    fn unit_balance(&self) -> UnitBalanceTableHandle<'_>;
}

impl UnitBalanceTableAccess for super::RemoteTables {
    fn unit_balance(&self) -> UnitBalanceTableHandle<'_> {
        UnitBalanceTableHandle {
            imp: self.imp.get_table::<TUnitBalance>("unit_balance"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UnitBalanceInsertCallbackId(__sdk::callbacks::CallbackId);
pub struct UnitBalanceDeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for UnitBalanceTableHandle<'ctx> {
    type Row = TUnitBalance;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TUnitBalance> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UnitBalanceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UnitBalanceInsertCallbackId {
        UnitBalanceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UnitBalanceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UnitBalanceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UnitBalanceDeleteCallbackId {
        UnitBalanceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UnitBalanceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct UnitBalanceUpdateCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::TableWithPrimaryKey for UnitBalanceTableHandle<'ctx> {
    type UpdateCallbackId = UnitBalanceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UnitBalanceUpdateCallbackId {
        UnitBalanceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UnitBalanceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<TUnitBalance>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_with_primary_key::<u64>(
        raw_updates,
        |row: &TUnitBalance| &row.id,
    )
    .context("Failed to parse table update for table \"unit_balance\"")
}

/// Access to the `id` unique index on the table `unit_balance`,
/// which allows point queries on the field of the same name
/// via the [`UnitBalanceIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.unit_balance().id().find(...)`.
pub struct UnitBalanceIdUnique<'ctx> {
    imp: __sdk::client_cache::UniqueConstraint<TUnitBalance, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UnitBalanceTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `unit_balance`.
    pub fn id(&self) -> UnitBalanceIdUnique<'ctx> {
        UnitBalanceIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id", |row| &row.id),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UnitBalanceIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TUnitBalance> {
        self.imp.find(col_val)
    }
}
