// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::t_unit_shard_item_type::TUnitShardItem;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `unit_shard_item`.
///
/// Obtain a handle from the [`UnitShardItemTableAccess::unit_shard_item`] method on [`super::RemoteTables`],
/// like `ctx.db.unit_shard_item()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.unit_shard_item().on_insert(...)`.
pub struct UnitShardItemTableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<TUnitShardItem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `unit_shard_item`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UnitShardItemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UnitShardItemTableHandle`], which mediates access to the table `unit_shard_item`.
    fn unit_shard_item(&self) -> UnitShardItemTableHandle<'_>;
}

impl UnitShardItemTableAccess for super::RemoteTables {
    fn unit_shard_item(&self) -> UnitShardItemTableHandle<'_> {
        UnitShardItemTableHandle {
            imp: self.imp.get_table::<TUnitShardItem>("unit_shard_item"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UnitShardItemInsertCallbackId(__sdk::callbacks::CallbackId);
pub struct UnitShardItemDeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for UnitShardItemTableHandle<'ctx> {
    type Row = TUnitShardItem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TUnitShardItem> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UnitShardItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UnitShardItemInsertCallbackId {
        UnitShardItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UnitShardItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UnitShardItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UnitShardItemDeleteCallbackId {
        UnitShardItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UnitShardItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct UnitShardItemUpdateCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::TableWithPrimaryKey for UnitShardItemTableHandle<'ctx> {
    type UpdateCallbackId = UnitShardItemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UnitShardItemUpdateCallbackId {
        UnitShardItemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UnitShardItemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<TUnitShardItem>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_with_primary_key::<u64>(
        raw_updates,
        |row: &TUnitShardItem| &row.id,
    )
    .context("Failed to parse table update for table \"unit_shard_item\"")
}

/// Access to the `id` unique index on the table `unit_shard_item`,
/// which allows point queries on the field of the same name
/// via the [`UnitShardItemIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.unit_shard_item().id().find(...)`.
pub struct UnitShardItemIdUnique<'ctx> {
    imp: __sdk::client_cache::UniqueConstraint<TUnitShardItem, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UnitShardItemTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `unit_shard_item`.
    pub fn id(&self) -> UnitShardItemIdUnique<'ctx> {
        UnitShardItemIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id", |row| &row.id),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UnitShardItemIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TUnitShardItem> {
        self.imp.find(col_val)
    }
}
