// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::global_settings::GlobalSettings;
use super::t_ability::TAbility;
use super::t_base_unit::TBaseUnit;
use super::t_house::THouse;
use super::t_representation::TRepresentation;
use super::t_status::TStatus;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address, ScheduleAt,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct UploadAssetsArgs {
    pub global_settings: GlobalSettings,
    pub representation: Vec<TRepresentation>,
    pub base_unit: Vec<TBaseUnit>,
    pub house: Vec<THouse>,
    pub ability: Vec<TAbility>,
    pub status: Vec<TStatus>,
}

impl Reducer for UploadAssetsArgs {
    const REDUCER_NAME: &'static str = "upload_assets";
}

#[allow(unused)]
pub fn upload_assets(
    global_settings: GlobalSettings,
    representation: Vec<TRepresentation>,
    base_unit: Vec<TBaseUnit>,
    house: Vec<THouse>,
    ability: Vec<TAbility>,
    status: Vec<TStatus>,
) {
    UploadAssetsArgs {
        global_settings,
        representation,
        base_unit,
        house,
        ability,
        status,
    }
    .invoke();
}

#[allow(unused)]
pub fn on_upload_assets(
    mut __callback: impl FnMut(
            &Identity,
            Option<Address>,
            &Status,
            &GlobalSettings,
            &Vec<TRepresentation>,
            &Vec<TBaseUnit>,
            &Vec<THouse>,
            &Vec<TAbility>,
            &Vec<TStatus>,
        ) + Send
        + 'static,
) -> ReducerCallbackId<UploadAssetsArgs> {
    UploadAssetsArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let UploadAssetsArgs {
            global_settings,
            representation,
            base_unit,
            house,
            ability,
            status,
        } = __args;
        __callback(
            __identity,
            __addr,
            __status,
            global_settings,
            representation,
            base_unit,
            house,
            ability,
            status,
        );
    })
}

#[allow(unused)]
pub fn once_on_upload_assets(
    __callback: impl FnOnce(
            &Identity,
            Option<Address>,
            &Status,
            &GlobalSettings,
            &Vec<TRepresentation>,
            &Vec<TBaseUnit>,
            &Vec<THouse>,
            &Vec<TAbility>,
            &Vec<TStatus>,
        ) + Send
        + 'static,
) -> ReducerCallbackId<UploadAssetsArgs> {
    UploadAssetsArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let UploadAssetsArgs {
            global_settings,
            representation,
            base_unit,
            house,
            ability,
            status,
        } = __args;
        __callback(
            __identity,
            __addr,
            __status,
            global_settings,
            representation,
            base_unit,
            house,
            ability,
            status,
        );
    })
}

#[allow(unused)]
pub fn remove_on_upload_assets(id: ReducerCallbackId<UploadAssetsArgs>) {
    UploadAssetsArgs::remove_on_reducer(id);
}
