// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::t_wallet_type::TWallet;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `wallet`.
///
/// Obtain a handle from the [`WalletTableAccess::wallet`] method on [`super::RemoteTables`],
/// like `ctx.db.wallet()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.wallet().on_insert(...)`.
pub struct WalletTableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<TWallet>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `wallet`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WalletTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WalletTableHandle`], which mediates access to the table `wallet`.
    fn wallet(&self) -> WalletTableHandle<'_>;
}

impl WalletTableAccess for super::RemoteTables {
    fn wallet(&self) -> WalletTableHandle<'_> {
        WalletTableHandle {
            imp: self.imp.get_table::<TWallet>("wallet"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WalletInsertCallbackId(__sdk::callbacks::CallbackId);
pub struct WalletDeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for WalletTableHandle<'ctx> {
    type Row = TWallet;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TWallet> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WalletInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WalletInsertCallbackId {
        WalletInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WalletInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WalletDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WalletDeleteCallbackId {
        WalletDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WalletDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WalletUpdateCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::TableWithPrimaryKey for WalletTableHandle<'ctx> {
    type UpdateCallbackId = WalletUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WalletUpdateCallbackId {
        WalletUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WalletUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<TWallet>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_with_primary_key::<u64>(
        raw_updates,
        |row: &TWallet| &row.owner,
    )
    .context("Failed to parse table update for table \"wallet\"")
}

/// Access to the `owner` unique index on the table `wallet`,
/// which allows point queries on the field of the same name
/// via the [`WalletOwnerUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.wallet().owner().find(...)`.
pub struct WalletOwnerUnique<'ctx> {
    imp: __sdk::client_cache::UniqueConstraint<TWallet, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WalletTableHandle<'ctx> {
    /// Get a handle on the `owner` unique index on the table `wallet`.
    pub fn owner(&self) -> WalletOwnerUnique<'ctx> {
        WalletOwnerUnique {
            imp: self
                .imp
                .get_unique_constraint::<u64>("owner", |row| &row.owner),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WalletOwnerUnique<'ctx> {
    /// Find the subscribed row whose `owner` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TWallet> {
        self.imp.find(col_val)
    }
}
