#!/usr/bin/env node
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
const require=createRequire(import.meta.url);let chromium;try{({chromium}=require('playwright'))}catch{({chromium}=require(process.env.ARENA_PLAYWRIGHT||'/root/work/arena-of-ideas/node_modules/playwright'))}
const root=dirname(fileURLToPath(import.meta.url)),repo=join(root,'../..'),html=join(root,'gallery.html'),captures=join(root,'captures');mkdirSync(captures,{recursive:true});
const output=[],log=s=>{console.log(s);output.push(s)},fail=(scope,msg)=>{throw Error(`[${scope}] ${msg}`)},source=readFileSync(html,'utf8');
const rgb=hex=>{const n=parseInt(hex.slice(1),16);return `rgb(${n>>16}, ${(n>>8)&255}, ${n&255})`};
try{
 log('=== AOI-S22 PASS 5 OBJECTIVE CHECK ===');
 for(const text of ['A · Market Promenade','B · Decision Ledger','C · Orbit Bench','Strength:','Risk:','Anti-reference:','Quiet Constellation','Run Spine','Portrait Ledger v2','Causal Atlas','Split Brief','Reroll · 1g','Save team','Fight Mira','Disabled reroll','Empty shop','Save failed','Fused A+B','Awakened · 3/3','equal parents'])if(!source.includes(text))fail('structure',`missing ${text}`);
 if((source.match(/data-thesis=/g)||[]).length!==3)fail('structure','not exactly three named theses');
 if(/<(script|link)[^>]+(src|href)=["']https?:/i.test(source))fail('self-contained','external runtime dependency');
 for(const token of ['--pwr:#ffc76a','--pwr-off:#e2c980','--hp:#ff7d72'])if(!source.includes(token))fail('tokens',`missing ${token}`);
 const candidate=JSON.parse(readFileSync(join(repo,'candidates/frostbite-striker.json'),'utf8')),frost=candidate.units.find(x=>x.name==='Frostbiter');
 const stress=readFileSync(join(repo,'src/content/stress.ts'),'utf8'),run=readFileSync(join(repo,'src/run.ts'),'utf8'),tunables=readFileSync(join(repo,'src/tunables.ts'),'utf8'),battle=readFileSync(join(repo,'src/battle.ts'),'utf8'),teams=readFileSync(join(repo,'web/teams.ts'),'utf8');
 if(frost.base.pwr!==2||frost.base.hp!==11||frost.statuses[0]?.status!=='Shield'||frost.statuses[0]?.stacks!==3)fail('truth','Frostbiter source drift');
 for(const seam of ['Venomancer: UnitDef = { name: "Venomancer", base: { hp: 6, pwr: 1 }','Summoner: UnitDef = { name: "Summoner", base: { hp: 6, pwr: 1 }','Silencer: UnitDef = { name: "Silencer", base: { hp: 8, pwr: 2 }','Necromancer: UnitDef = { name: "Necromancer", base: { hp: 7, pwr: 1 }','Imp: UnitDef = { name: "Imp", base: { hp: 2, pwr: 1 }'])if(!stress.includes(seam))fail('truth',`stress seam ${seam}`);
 for(const seam of ['export const UNIT_COST = 3','export const REROLL_COST = 1','export const SHOP_SIZE_BASE = 3','export const SHOP_SIZE_MAX = 6','name: "Warden", base: { hp: 17, pwr: 5 }'])if(!tunables.includes(seam))fail('truth',`tunable seam ${seam}`);
 if(!battle.includes('export const TEAM_SIZE = 5'))fail('truth','team size source drift');
 if(!run.includes('first.base.hp + second.base.hp')||!run.includes('first.base.pwr + second.base.pwr')||!run.includes('meter: 0'))fail('truth','fusion additive/meter seam drift');
 for(const seam of ['u.kind === "composite" && u.fusion!.parents.some((p) => p.name === def.name)','u.kind === "base" && u.name === def.name','target < 0 && state.team.length >= TEAM_SIZE','u.base.pwr += 1','u.base.hp += 2','fusion.meter += 1'])if(!run.includes(seam))fail('truth',`buy routing seam ${seam}`);
 if(!teams.includes('localStorage')&&!teams.includes('STORAGE_KEY'))fail('truth','saved-team production seam absent');
 log('source/truth: PASS exactly three compositions; self-contained; tokens and Frostbiter/stress/tunable/fusion meter 0/buy routing/team/save seams match production');
 const browser=await chromium.launch({headless:true});
 try{
  const stances=['promenade','ledger','orbit'],views=[{name:'desktop',w:1440,h:1000},{name:'phone',w:390,h:844}];let fixtureFingerprint;
  for(const stance of stances)for(const view of views){
   const page=await browser.newPage({viewport:{width:view.w,height:view.h},reducedMotion:'reduce'});await page.goto(`${pathToFileURL(html).href}?stance=${stance}`);
   const result=await page.evaluate(()=>{const q=s=>[...document.querySelectorAll(s)],visible=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'},box=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom,w:r.width,h:r.height}},text=e=>e.textContent.replace(/\s+/g,' ').trim();const shop=box(document.querySelector('.offers')),decision=box(document.querySelector('.decision')),team=box(document.querySelector('.team-zone'));const targets=q('button').filter(visible).map(e=>({text:text(e),...box(e)}));const leaves=q('body *').filter(e=>visible(e)&&e.children.length===0&&text(e)).map(e=>({text:text(e),font:parseFloat(getComputedStyle(e).fontSize),sw:e.scrollWidth,cw:e.clientWidth,sh:e.scrollHeight,ch:e.clientHeight,intentional:!!e.closest('.long,.offers,.team')}));return{stance:document.body.dataset.stance,scrollW:document.documentElement.scrollWidth,offers:q('.offer:not([hidden])').length,totalOffers:q('.offer').length,team:q('.team .card').length,proofs:q('.proof').length,comparison:visible(document.querySelector('.comparison')),causal:q('.decision .step').length,shop,decision,teamBox:team,targets,leaves,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,pwr:getComputedStyle(document.querySelector('.pwr')).color,hp:getComputedStyle(document.querySelector('.hp')).color,activeThesis:q('.theses .active').length,activeTrade:q('.tradeoffs .active').length,fingerprint:JSON.stringify({offers:q('.offer').map(text),team:q('.team .card').map(text),stakes:text(document.querySelector('.stakes')),selected:text(document.querySelector('.decision')),proofs:q('.proof').map(text)})};});
   if(result.stance!==stance||result.scrollW>view.w)fail(`${stance}/${view.name}`,`stance/page overflow ${result.scrollW}/${view.w}`);
   if(result.offers!==6||result.totalOffers!==6||result.team!==5||result.proofs!==3||!result.comparison||result.causal!==3)fail(`${stance}/${view.name}`,'fixture structure mismatch');
   if(fixtureFingerprint===undefined)fixtureFingerprint=result.fingerprint;else if(result.fingerprint!==fixtureFingerprint)fail(`${stance}/${view.name}`,'fixture differs across composition/view');
   if(result.pwr!==rgb('#ffc76a')||result.hp!==rgb('#ff7d72'))fail(`${stance}/${view.name}`,`stat colors ${result.pwr}/${result.hp}`);
   if(!result.reduced)fail(`${stance}/${view.name}`,'reduced-motion media false');
   if(result.targets.some(x=>x.w<40||x.h<40))fail(`${stance}/${view.name}`,`target floor ${JSON.stringify(result.targets.filter(x=>x.w<40||x.h<40).slice(0,4))}`);
   const clipped=result.leaves.filter(x=>!x.intentional&&x.sw>x.cw+3);if(clipped.length)fail(`${stance}/${view.name}`,`text clipping ${JSON.stringify(clipped.slice(0,4))}`);
   if(result.leaves.some(x=>x.font<9))fail(`${stance}/${view.name}`,'text below 9px specimen floor');
   if(result.shop.y>result.decision.y+2||result.decision.y>result.teamBox.y+2)fail(`${stance}/${view.name}`,`shop → decision → team order broken`);
   if(view.name==='desktop'&&(result.activeThesis!==1||result.activeTrade!==1))fail(`${stance}/desktop`,'active stance notes');
   for(let n=3;n<=6;n++){await page.locator(`[data-count="${n}"]`).click();if(await page.locator('.offer:visible').count()!==n)fail(`${stance}/${view.name}`,`offer count ${n}`)}
   await page.locator('[data-count="6"]').click();
   await page.locator('.offer').nth(5).click();if(!await page.locator('.buy').isDisabled()||!(await page.locator('#consequence').innerText()).includes('Cannot buy')||!(await page.locator('#comparison-copy').innerText()).includes('full (5/5)')||!(await page.locator('#comparison-copy').innerText()).includes('rejected'))fail('interaction','full-team no-match Buy is not disabled with adjacent rejection reason');
   await page.locator('.offer').nth(0).click();if(await page.locator('.buy').isDisabled()||!(await page.locator('#comparison-copy').innerText()).includes('+1 PWR / +2 HP')||!(await page.locator('#comparison-copy').innerText()).includes('0/3 to 1/3'))fail('interaction','composite-parent Buy routing/consequence');
   await page.locator('.offer').nth(4).click();if(await page.locator('.buy').isDisabled()||!(await page.locator('#selected-name').innerText()).includes('Last Lantern')||!(await page.locator('#consequence').innerText()).includes('3g remains')||!(await page.locator('#comparison-copy').innerText()).includes('1/3 to 2/3'))fail('interaction','owned-base Buy routing/long selection consequence update');
   for(let i=0;i<await page.locator('button:visible:not([disabled])').count();i++){const b=page.locator('button:visible:not([disabled])').nth(i);await b.focus();if(!await b.evaluate(e=>document.activeElement===e&&parseFloat(getComputedStyle(e).outlineWidth)>=3))fail(`${stance}/${view.name}`,`focus ${await b.innerText()}`)}
   await page.evaluate(()=>{scrollTo(0,0);document.activeElement?.blur()});await page.screenshot({path:join(captures,`${stance}-${view.name}.png`),fullPage:true});
   if(view.name==='phone'){const inspect=page.locator('.inspect');await inspect.scrollIntoViewIfNeeded();await inspect.click();if(!await page.locator('.close').evaluate(e=>document.activeElement===e))fail('interaction','phone inspector close-first');if(await page.locator('.inspector').getAttribute('aria-modal')!=='true')fail('interaction','phone inspector not modal');await page.keyboard.press('Shift+Tab');if(!await page.locator('.close').evaluate(e=>document.activeElement===e))fail('interaction','phone inspector reverse trap');await page.screenshot({path:join(captures,`${stance}-phone-inspector.png`)});await page.keyboard.press('Escape');if(!await inspect.evaluate(e=>document.activeElement===e)||await page.locator('.inspector').isVisible())fail('interaction','Escape/focus return');}
   await page.close();log(`${stance}/${view.name}: PASS geometry, no page/text overflow, order, 3–6 offers, fixture, targets, text, focus, reduced motion`);
  }
  log('interaction: PASS full-team no-match Buy disabled with adjacent rejection reason; owned base/composite routes enabled with +1/+2 and meter consequences; phone Causal Atlas sheet focus behavior');
 }finally{await browser.close()}
 const status=execFileSync('git',['status','--porcelain','--untracked-files=all'],{cwd:repo,encoding:'utf8'}).trim().split('\n').filter(Boolean);const bad=status.map(x=>x.slice(3)).filter(x=>!x.startsWith('design/aoi-s22-pass-5/')&&!x.startsWith('.pi-subagents/'));if(bad.length)fail('isolation',`non-artifact paths ${bad.join(', ')}`);const staged=execFileSync('git',['diff','--cached','--name-only'],{cwd:repo,encoding:'utf8'}).trim();if(staged)fail('isolation',`staged paths ${staged}`);log('production isolation: PASS only design/aoi-s22-pass-5/ changed (runtime .pi-subagents ignored); no staged files');
 const files=readdirSync(captures).filter(x=>x.endsWith('.png')).sort();if(files.length!==9)fail('captures',`expected 9 PNGs, found ${files.length}`);const manifest=files.map(f=>{const p=join(captures,f),buf=readFileSync(p);return `${f}\t${statSync(p).size} bytes\tsha256 ${createHash('sha256').update(buf).digest('hex')}`}).join('\n')+'\n';writeFileSync(join(root,'capture-manifest.txt'),manifest);log('captures: PASS 9 real Chromium PNGs (3 desktop + 3 phone + 3 phone inspector), SHA-256 manifest written');log('DESIGN QUALITY: UNJUDGED BY MACHINE — manual capture inspection and independent review remain separate gates.');
}catch(e){log(`FAIL ${e.stack||e}`);process.exitCode=1}finally{writeFileSync(join(root,'check-output.txt'),output.join('\n')+'\n')}
