// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AbilityDeleteArgs {
    pub ability_id: u64,
}

impl From<AbilityDeleteArgs> for super::Reducer {
    fn from(args: AbilityDeleteArgs) -> Self {
        Self::AbilityDelete {
            ability_id: args.ability_id,
        }
    }
}

impl __sdk::InModule for AbilityDeleteArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ability_delete`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ability_delete {
    /// Request that the remote module invoke the reducer `ability_delete` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ability_delete:ability_delete_then`] to run a callback after the reducer completes.
    fn ability_delete(&self, ability_id: u64) -> __sdk::Result<()> {
        self.ability_delete_then(ability_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `ability_delete` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ability_delete_then(
        &self,
        ability_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ability_delete for super::RemoteReducers {
    fn ability_delete_then(
        &self,
        ability_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AbilityDeleteArgs { ability_id }, callback)
    }
}
