// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::content_status_type::ContentStatus;
use super::target_type_type::TargetType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Ability {
    pub id: u64,
    pub name: String,
    pub description: String,
    pub target_type: TargetType,
    pub effect_script: String,
    pub parent_a: u64,
    pub parent_b: u64,
    pub rating: i32,
    pub status: ContentStatus,
    pub season: u32,
    pub created_by: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for Ability {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Ability`.
///
/// Provides typed access to columns for query building.
pub struct AbilityCols {
    pub id: __sdk::__query_builder::Col<Ability, u64>,
    pub name: __sdk::__query_builder::Col<Ability, String>,
    pub description: __sdk::__query_builder::Col<Ability, String>,
    pub target_type: __sdk::__query_builder::Col<Ability, TargetType>,
    pub effect_script: __sdk::__query_builder::Col<Ability, String>,
    pub parent_a: __sdk::__query_builder::Col<Ability, u64>,
    pub parent_b: __sdk::__query_builder::Col<Ability, u64>,
    pub rating: __sdk::__query_builder::Col<Ability, i32>,
    pub status: __sdk::__query_builder::Col<Ability, ContentStatus>,
    pub season: __sdk::__query_builder::Col<Ability, u32>,
    pub created_by: __sdk::__query_builder::Col<Ability, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<Ability, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Ability {
    type Cols = AbilityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AbilityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            target_type: __sdk::__query_builder::Col::new(table_name, "target_type"),
            effect_script: __sdk::__query_builder::Col::new(table_name, "effect_script"),
            parent_a: __sdk::__query_builder::Col::new(table_name, "parent_a"),
            parent_b: __sdk::__query_builder::Col::new(table_name, "parent_b"),
            rating: __sdk::__query_builder::Col::new(table_name, "rating"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            season: __sdk::__query_builder::Col::new(table_name, "season"),
            created_by: __sdk::__query_builder::Col::new(table_name, "created_by"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Ability`.
///
/// Provides typed access to indexed columns for query building.
pub struct AbilityIxCols {
    pub id: __sdk::__query_builder::IxCol<Ability, u64>,
    pub name: __sdk::__query_builder::IxCol<Ability, String>,
}

impl __sdk::__query_builder::HasIxCols for Ability {
    type IxCols = AbilityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AbilityIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Ability {}
