// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ability_type::Ability;
use super::content_status_type::ContentStatus;
use super::target_type_type::TargetType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ability`.
///
/// Obtain a handle from the [`AbilityTableAccess::ability`] method on [`super::RemoteTables`],
/// like `ctx.db.ability()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ability().on_insert(...)`.
pub struct AbilityTableHandle<'ctx> {
    imp: __sdk::TableHandle<Ability>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ability`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AbilityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AbilityTableHandle`], which mediates access to the table `ability`.
    fn ability(&self) -> AbilityTableHandle<'_>;
}

impl AbilityTableAccess for super::RemoteTables {
    fn ability(&self) -> AbilityTableHandle<'_> {
        AbilityTableHandle {
            imp: self.imp.get_table::<Ability>("ability"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AbilityInsertCallbackId(__sdk::CallbackId);
pub struct AbilityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AbilityTableHandle<'ctx> {
    type Row = Ability;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Ability> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AbilityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AbilityInsertCallbackId {
        AbilityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AbilityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AbilityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AbilityDeleteCallbackId {
        AbilityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AbilityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AbilityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AbilityTableHandle<'ctx> {
    type UpdateCallbackId = AbilityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AbilityUpdateCallbackId {
        AbilityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AbilityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ability`,
/// which allows point queries on the field of the same name
/// via the [`AbilityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ability().id().find(...)`.
pub struct AbilityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Ability, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AbilityTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ability`.
    pub fn id(&self) -> AbilityIdUnique<'ctx> {
        AbilityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AbilityIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Ability> {
        self.imp.find(col_val)
    }
}

/// Access to the `name` unique index on the table `ability`,
/// which allows point queries on the field of the same name
/// via the [`AbilityNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ability().name().find(...)`.
pub struct AbilityNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Ability, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AbilityTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `ability`.
    pub fn name(&self) -> AbilityNameUnique<'ctx> {
        AbilityNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AbilityNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Ability> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Ability>("ability");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Ability>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Ability>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Ability`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait abilityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Ability`.
    fn ability(&self) -> __sdk::__query_builder::Table<Ability>;
}

impl abilityQueryTableAccess for __sdk::QueryTableAccessor {
    fn ability(&self) -> __sdk::__query_builder::Table<Ability> {
        __sdk::__query_builder::Table::new("ability")
    }
}
