// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::arena_state_type::ArenaState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `arena_state`.
///
/// Obtain a handle from the [`ArenaStateTableAccess::arena_state`] method on [`super::RemoteTables`],
/// like `ctx.db.arena_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.arena_state().on_insert(...)`.
pub struct ArenaStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<ArenaState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `arena_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ArenaStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ArenaStateTableHandle`], which mediates access to the table `arena_state`.
    fn arena_state(&self) -> ArenaStateTableHandle<'_>;
}

impl ArenaStateTableAccess for super::RemoteTables {
    fn arena_state(&self) -> ArenaStateTableHandle<'_> {
        ArenaStateTableHandle {
            imp: self.imp.get_table::<ArenaState>("arena_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ArenaStateInsertCallbackId(__sdk::CallbackId);
pub struct ArenaStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ArenaStateTableHandle<'ctx> {
    type Row = ArenaState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ArenaState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ArenaStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ArenaStateInsertCallbackId {
        ArenaStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ArenaStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ArenaStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ArenaStateDeleteCallbackId {
        ArenaStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ArenaStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ArenaStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ArenaStateTableHandle<'ctx> {
    type UpdateCallbackId = ArenaStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ArenaStateUpdateCallbackId {
        ArenaStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ArenaStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `always_zero` unique index on the table `arena_state`,
/// which allows point queries on the field of the same name
/// via the [`ArenaStateAlwaysZeroUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.arena_state().always_zero().find(...)`.
pub struct ArenaStateAlwaysZeroUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ArenaState, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ArenaStateTableHandle<'ctx> {
    /// Get a handle on the `always_zero` unique index on the table `arena_state`.
    pub fn always_zero(&self) -> ArenaStateAlwaysZeroUnique<'ctx> {
        ArenaStateAlwaysZeroUnique {
            imp: self.imp.get_unique_constraint::<u32>("always_zero"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ArenaStateAlwaysZeroUnique<'ctx> {
    /// Find the subscribed row whose `always_zero` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<ArenaState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ArenaState>("arena_state");
    _table.add_unique_constraint::<u32>("always_zero", |row| &row.always_zero);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ArenaState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ArenaState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ArenaState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait arena_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ArenaState`.
    fn arena_state(&self) -> __sdk::__query_builder::Table<ArenaState>;
}

impl arena_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn arena_state(&self) -> __sdk::__query_builder::Table<ArenaState> {
        __sdk::__query_builder::Table::new("arena_state")
    }
}
