// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::feature_request_type::FeatureRequest;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `feature_request`.
///
/// Obtain a handle from the [`FeatureRequestTableAccess::feature_request`] method on [`super::RemoteTables`],
/// like `ctx.db.feature_request()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.feature_request().on_insert(...)`.
pub struct FeatureRequestTableHandle<'ctx> {
    imp: __sdk::TableHandle<FeatureRequest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `feature_request`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FeatureRequestTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FeatureRequestTableHandle`], which mediates access to the table `feature_request`.
    fn feature_request(&self) -> FeatureRequestTableHandle<'_>;
}

impl FeatureRequestTableAccess for super::RemoteTables {
    fn feature_request(&self) -> FeatureRequestTableHandle<'_> {
        FeatureRequestTableHandle {
            imp: self.imp.get_table::<FeatureRequest>("feature_request"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FeatureRequestInsertCallbackId(__sdk::CallbackId);
pub struct FeatureRequestDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FeatureRequestTableHandle<'ctx> {
    type Row = FeatureRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FeatureRequest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FeatureRequestInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FeatureRequestInsertCallbackId {
        FeatureRequestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FeatureRequestInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FeatureRequestDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FeatureRequestDeleteCallbackId {
        FeatureRequestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FeatureRequestDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct FeatureRequestUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FeatureRequestTableHandle<'ctx> {
    type UpdateCallbackId = FeatureRequestUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FeatureRequestUpdateCallbackId {
        FeatureRequestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FeatureRequestUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `feature_request`,
/// which allows point queries on the field of the same name
/// via the [`FeatureRequestIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.feature_request().id().find(...)`.
pub struct FeatureRequestIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FeatureRequest, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FeatureRequestTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `feature_request`.
    pub fn id(&self) -> FeatureRequestIdUnique<'ctx> {
        FeatureRequestIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FeatureRequestIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<FeatureRequest> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FeatureRequest>("feature_request");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FeatureRequest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FeatureRequest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FeatureRequest`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait feature_requestQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FeatureRequest`.
    fn feature_request(&self) -> __sdk::__query_builder::Table<FeatureRequest>;
}

impl feature_requestQueryTableAccess for __sdk::QueryTableAccessor {
    fn feature_request(&self) -> __sdk::__query_builder::Table<FeatureRequest> {
        __sdk::__query_builder::Table::new("feature_request")
    }
}
