// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct FeatureRequestAcceptArgs {
    pub request_id: u64,
}

impl From<FeatureRequestAcceptArgs> for super::Reducer {
    fn from(args: FeatureRequestAcceptArgs) -> Self {
        Self::FeatureRequestAccept {
            request_id: args.request_id,
        }
    }
}

impl __sdk::InModule for FeatureRequestAcceptArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `feature_request_accept`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait feature_request_accept {
    /// Request that the remote module invoke the reducer `feature_request_accept` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`feature_request_accept:feature_request_accept_then`] to run a callback after the reducer completes.
    fn feature_request_accept(&self, request_id: u64) -> __sdk::Result<()> {
        self.feature_request_accept_then(request_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `feature_request_accept` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn feature_request_accept_then(
        &self,
        request_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl feature_request_accept for super::RemoteReducers {
    fn feature_request_accept_then(
        &self,
        request_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(FeatureRequestAcceptArgs { request_id }, callback)
    }
}
