// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::floor_pool_team_type::FloorPoolTeam;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `floor_pool_team`.
///
/// Obtain a handle from the [`FloorPoolTeamTableAccess::floor_pool_team`] method on [`super::RemoteTables`],
/// like `ctx.db.floor_pool_team()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.floor_pool_team().on_insert(...)`.
pub struct FloorPoolTeamTableHandle<'ctx> {
    imp: __sdk::TableHandle<FloorPoolTeam>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `floor_pool_team`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FloorPoolTeamTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FloorPoolTeamTableHandle`], which mediates access to the table `floor_pool_team`.
    fn floor_pool_team(&self) -> FloorPoolTeamTableHandle<'_>;
}

impl FloorPoolTeamTableAccess for super::RemoteTables {
    fn floor_pool_team(&self) -> FloorPoolTeamTableHandle<'_> {
        FloorPoolTeamTableHandle {
            imp: self.imp.get_table::<FloorPoolTeam>("floor_pool_team"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FloorPoolTeamInsertCallbackId(__sdk::CallbackId);
pub struct FloorPoolTeamDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FloorPoolTeamTableHandle<'ctx> {
    type Row = FloorPoolTeam;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FloorPoolTeam> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FloorPoolTeamInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FloorPoolTeamInsertCallbackId {
        FloorPoolTeamInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FloorPoolTeamInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FloorPoolTeamDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FloorPoolTeamDeleteCallbackId {
        FloorPoolTeamDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FloorPoolTeamDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct FloorPoolTeamUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FloorPoolTeamTableHandle<'ctx> {
    type UpdateCallbackId = FloorPoolTeamUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FloorPoolTeamUpdateCallbackId {
        FloorPoolTeamUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FloorPoolTeamUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `floor_pool_team`,
/// which allows point queries on the field of the same name
/// via the [`FloorPoolTeamIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.floor_pool_team().id().find(...)`.
pub struct FloorPoolTeamIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FloorPoolTeam, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FloorPoolTeamTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `floor_pool_team`.
    pub fn id(&self) -> FloorPoolTeamIdUnique<'ctx> {
        FloorPoolTeamIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FloorPoolTeamIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<FloorPoolTeam> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FloorPoolTeam>("floor_pool_team");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FloorPoolTeam>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FloorPoolTeam>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FloorPoolTeam`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait floor_pool_teamQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FloorPoolTeam`.
    fn floor_pool_team(&self) -> __sdk::__query_builder::Table<FloorPoolTeam>;
}

impl floor_pool_teamQueryTableAccess for __sdk::QueryTableAccessor {
    fn floor_pool_team(&self) -> __sdk::__query_builder::Table<FloorPoolTeam> {
        __sdk::__query_builder::Table::new("floor_pool_team")
    }
}
