// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::floor_boss_type::FloorBoss;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `floor_boss`.
///
/// Obtain a handle from the [`FloorBossTableAccess::floor_boss`] method on [`super::RemoteTables`],
/// like `ctx.db.floor_boss()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.floor_boss().on_insert(...)`.
pub struct FloorBossTableHandle<'ctx> {
    imp: __sdk::TableHandle<FloorBoss>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `floor_boss`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FloorBossTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FloorBossTableHandle`], which mediates access to the table `floor_boss`.
    fn floor_boss(&self) -> FloorBossTableHandle<'_>;
}

impl FloorBossTableAccess for super::RemoteTables {
    fn floor_boss(&self) -> FloorBossTableHandle<'_> {
        FloorBossTableHandle {
            imp: self.imp.get_table::<FloorBoss>("floor_boss"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FloorBossInsertCallbackId(__sdk::CallbackId);
pub struct FloorBossDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FloorBossTableHandle<'ctx> {
    type Row = FloorBoss;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FloorBoss> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FloorBossInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FloorBossInsertCallbackId {
        FloorBossInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FloorBossInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FloorBossDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FloorBossDeleteCallbackId {
        FloorBossDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FloorBossDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct FloorBossUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FloorBossTableHandle<'ctx> {
    type UpdateCallbackId = FloorBossUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FloorBossUpdateCallbackId {
        FloorBossUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FloorBossUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `floor_boss`,
/// which allows point queries on the field of the same name
/// via the [`FloorBossIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.floor_boss().id().find(...)`.
pub struct FloorBossIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FloorBoss, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FloorBossTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `floor_boss`.
    pub fn id(&self) -> FloorBossIdUnique<'ctx> {
        FloorBossIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FloorBossIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<FloorBoss> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FloorBoss>("floor_boss");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FloorBoss>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FloorBoss>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FloorBoss`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait floor_bossQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FloorBoss`.
    fn floor_boss(&self) -> __sdk::__query_builder::Table<FloorBoss>;
}

impl floor_bossQueryTableAccess for __sdk::QueryTableAccessor {
    fn floor_boss(&self) -> __sdk::__query_builder::Table<FloorBoss> {
        __sdk::__query_builder::Table::new("floor_boss")
    }
}
