// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::match_state_type::MatchState;
use super::team_slot_type::TeamSlot;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GameMatch {
    pub id: u64,
    pub player: __sdk::Identity,
    pub floor: u8,
    pub gold: i32,
    pub lives: i32,
    pub state: MatchState,
    pub team: Vec<TeamSlot>,
    pub shop_offers: Vec<u64>,
    pub pending_battle_id: u64,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for GameMatch {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GameMatch`.
///
/// Provides typed access to columns for query building.
pub struct GameMatchCols {
    pub id: __sdk::__query_builder::Col<GameMatch, u64>,
    pub player: __sdk::__query_builder::Col<GameMatch, __sdk::Identity>,
    pub floor: __sdk::__query_builder::Col<GameMatch, u8>,
    pub gold: __sdk::__query_builder::Col<GameMatch, i32>,
    pub lives: __sdk::__query_builder::Col<GameMatch, i32>,
    pub state: __sdk::__query_builder::Col<GameMatch, MatchState>,
    pub team: __sdk::__query_builder::Col<GameMatch, Vec<TeamSlot>>,
    pub shop_offers: __sdk::__query_builder::Col<GameMatch, Vec<u64>>,
    pub pending_battle_id: __sdk::__query_builder::Col<GameMatch, u64>,
    pub created_at: __sdk::__query_builder::Col<GameMatch, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for GameMatch {
    type Cols = GameMatchCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GameMatchCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            player: __sdk::__query_builder::Col::new(table_name, "player"),
            floor: __sdk::__query_builder::Col::new(table_name, "floor"),
            gold: __sdk::__query_builder::Col::new(table_name, "gold"),
            lives: __sdk::__query_builder::Col::new(table_name, "lives"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            team: __sdk::__query_builder::Col::new(table_name, "team"),
            shop_offers: __sdk::__query_builder::Col::new(table_name, "shop_offers"),
            pending_battle_id: __sdk::__query_builder::Col::new(table_name, "pending_battle_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `GameMatch`.
///
/// Provides typed access to indexed columns for query building.
pub struct GameMatchIxCols {
    pub id: __sdk::__query_builder::IxCol<GameMatch, u64>,
}

impl __sdk::__query_builder::HasIxCols for GameMatch {
    type IxCols = GameMatchIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GameMatchIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GameMatch {}
