// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::gen_request_type::GenRequest;
use super::gen_status_type::GenStatus;
use super::gen_target_kind_type::GenTargetKind;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `gen_request`.
///
/// Obtain a handle from the [`GenRequestTableAccess::gen_request`] method on [`super::RemoteTables`],
/// like `ctx.db.gen_request()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gen_request().on_insert(...)`.
pub struct GenRequestTableHandle<'ctx> {
    imp: __sdk::TableHandle<GenRequest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `gen_request`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GenRequestTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GenRequestTableHandle`], which mediates access to the table `gen_request`.
    fn gen_request(&self) -> GenRequestTableHandle<'_>;
}

impl GenRequestTableAccess for super::RemoteTables {
    fn gen_request(&self) -> GenRequestTableHandle<'_> {
        GenRequestTableHandle {
            imp: self.imp.get_table::<GenRequest>("gen_request"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GenRequestInsertCallbackId(__sdk::CallbackId);
pub struct GenRequestDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GenRequestTableHandle<'ctx> {
    type Row = GenRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GenRequest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GenRequestInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GenRequestInsertCallbackId {
        GenRequestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GenRequestInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GenRequestDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GenRequestDeleteCallbackId {
        GenRequestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GenRequestDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GenRequestUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GenRequestTableHandle<'ctx> {
    type UpdateCallbackId = GenRequestUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GenRequestUpdateCallbackId {
        GenRequestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GenRequestUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `gen_request`,
/// which allows point queries on the field of the same name
/// via the [`GenRequestIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gen_request().id().find(...)`.
pub struct GenRequestIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GenRequest, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GenRequestTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `gen_request`.
    pub fn id(&self) -> GenRequestIdUnique<'ctx> {
        GenRequestIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GenRequestIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GenRequest> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GenRequest>("gen_request");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GenRequest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GenRequest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GenRequest`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait gen_requestQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GenRequest`.
    fn gen_request(&self) -> __sdk::__query_builder::Table<GenRequest>;
}

impl gen_requestQueryTableAccess for __sdk::QueryTableAccessor {
    fn gen_request(&self) -> __sdk::__query_builder::Table<GenRequest> {
        __sdk::__query_builder::Table::new("gen_request")
    }
}
