// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GenMarkFailedArgs {
    pub request_id: u64,
}

impl From<GenMarkFailedArgs> for super::Reducer {
    fn from(args: GenMarkFailedArgs) -> Self {
        Self::GenMarkFailed {
            request_id: args.request_id,
        }
    }
}

impl __sdk::InModule for GenMarkFailedArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `gen_mark_failed`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait gen_mark_failed {
    /// Request that the remote module invoke the reducer `gen_mark_failed` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`gen_mark_failed:gen_mark_failed_then`] to run a callback after the reducer completes.
    fn gen_mark_failed(&self, request_id: u64) -> __sdk::Result<()> {
        self.gen_mark_failed_then(request_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `gen_mark_failed` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn gen_mark_failed_then(
        &self,
        request_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl gen_mark_failed for super::RemoteReducers {
    fn gen_mark_failed_then(
        &self,
        request_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(GenMarkFailedArgs { request_id }, callback)
    }
}
