// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LoginByIdentityArgs {}

impl From<LoginByIdentityArgs> for super::Reducer {
    fn from(args: LoginByIdentityArgs) -> Self {
        Self::LoginByIdentity
    }
}

impl __sdk::InModule for LoginByIdentityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `login_by_identity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait login_by_identity {
    /// Request that the remote module invoke the reducer `login_by_identity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`login_by_identity:login_by_identity_then`] to run a callback after the reducer completes.
    fn login_by_identity(&self) -> __sdk::Result<()> {
        self.login_by_identity_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `login_by_identity` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn login_by_identity_then(
        &self,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl login_by_identity for super::RemoteReducers {
    fn login_by_identity_then(
        &self,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(LoginByIdentityArgs {}, callback)
    }
}
