// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MatchFeedUnitArgs {
    pub fused_slot: u32,
    pub donor_slot: u32,
}

impl From<MatchFeedUnitArgs> for super::Reducer {
    fn from(args: MatchFeedUnitArgs) -> Self {
        Self::MatchFeedUnit {
            fused_slot: args.fused_slot,
            donor_slot: args.donor_slot,
        }
    }
}

impl __sdk::InModule for MatchFeedUnitArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `match_feed_unit`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait match_feed_unit {
    /// Request that the remote module invoke the reducer `match_feed_unit` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`match_feed_unit:match_feed_unit_then`] to run a callback after the reducer completes.
    fn match_feed_unit(&self, fused_slot: u32, donor_slot: u32) -> __sdk::Result<()> {
        self.match_feed_unit_then(fused_slot, donor_slot, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `match_feed_unit` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn match_feed_unit_then(
        &self,
        fused_slot: u32,
        donor_slot: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl match_feed_unit for super::RemoteReducers {
    fn match_feed_unit_then(
        &self,
        fused_slot: u32,
        donor_slot: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            MatchFeedUnitArgs {
                fused_slot,
                donor_slot,
            },
            callback,
        )
    }
}
