// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::content_status_type::ContentStatus;
use super::trigger_type::Trigger;
use super::unit_type::Unit;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `unit`.
///
/// Obtain a handle from the [`UnitTableAccess::unit`] method on [`super::RemoteTables`],
/// like `ctx.db.unit()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.unit().on_insert(...)`.
pub struct UnitTableHandle<'ctx> {
    imp: __sdk::TableHandle<Unit>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `unit`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UnitTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UnitTableHandle`], which mediates access to the table `unit`.
    fn unit(&self) -> UnitTableHandle<'_>;
}

impl UnitTableAccess for super::RemoteTables {
    fn unit(&self) -> UnitTableHandle<'_> {
        UnitTableHandle {
            imp: self.imp.get_table::<Unit>("unit"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UnitInsertCallbackId(__sdk::CallbackId);
pub struct UnitDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UnitTableHandle<'ctx> {
    type Row = Unit;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Unit> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UnitInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UnitInsertCallbackId {
        UnitInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UnitInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UnitDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UnitDeleteCallbackId {
        UnitDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UnitDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct UnitUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UnitTableHandle<'ctx> {
    type UpdateCallbackId = UnitUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UnitUpdateCallbackId {
        UnitUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UnitUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `unit`,
/// which allows point queries on the field of the same name
/// via the [`UnitIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.unit().id().find(...)`.
pub struct UnitIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Unit, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UnitTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `unit`.
    pub fn id(&self) -> UnitIdUnique<'ctx> {
        UnitIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UnitIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Unit> {
        self.imp.find(col_val)
    }
}

/// Access to the `name` unique index on the table `unit`,
/// which allows point queries on the field of the same name
/// via the [`UnitNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.unit().name().find(...)`.
pub struct UnitNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Unit, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UnitTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `unit`.
    pub fn name(&self) -> UnitNameUnique<'ctx> {
        UnitNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UnitNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Unit> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Unit>("unit");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Unit>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Unit>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Unit`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait unitQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Unit`.
    fn unit(&self) -> __sdk::__query_builder::Table<Unit>;
}

impl unitQueryTableAccess for __sdk::QueryTableAccessor {
    fn unit(&self) -> __sdk::__query_builder::Table<Unit> {
        __sdk::__query_builder::Table::new("unit")
    }
}
