// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::trigger_type::Trigger;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UnitCreateArgs {
    pub name: String,
    pub description: String,
    pub hp: i32,
    pub pwr: i32,
    pub tier: u8,
    pub trigger: Trigger,
    pub abilities: Vec<u64>,
    pub painter_script: String,
}

impl From<UnitCreateArgs> for super::Reducer {
    fn from(args: UnitCreateArgs) -> Self {
        Self::UnitCreate {
            name: args.name,
            description: args.description,
            hp: args.hp,
            pwr: args.pwr,
            tier: args.tier,
            trigger: args.trigger,
            abilities: args.abilities,
            painter_script: args.painter_script,
        }
    }
}

impl __sdk::InModule for UnitCreateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `unit_create`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait unit_create {
    /// Request that the remote module invoke the reducer `unit_create` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`unit_create:unit_create_then`] to run a callback after the reducer completes.
    fn unit_create(
        &self,
        name: String,
        description: String,
        hp: i32,
        pwr: i32,
        tier: u8,
        trigger: Trigger,
        abilities: Vec<u64>,
        painter_script: String,
    ) -> __sdk::Result<()> {
        self.unit_create_then(
            name,
            description,
            hp,
            pwr,
            tier,
            trigger,
            abilities,
            painter_script,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `unit_create` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn unit_create_then(
        &self,
        name: String,
        description: String,
        hp: i32,
        pwr: i32,
        tier: u8,
        trigger: Trigger,
        abilities: Vec<u64>,
        painter_script: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl unit_create for super::RemoteReducers {
    fn unit_create_then(
        &self,
        name: String,
        description: String,
        hp: i32,
        pwr: i32,
        tier: u8,
        trigger: Trigger,
        abilities: Vec<u64>,
        painter_script: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UnitCreateArgs {
                name,
                description,
                hp,
                pwr,
                tier,
                trigger,
                abilities,
                painter_script,
            },
            callback,
        )
    }
}
