// Meta-health report for the MVP pool (mission #574, slice 7).
//
//   npm run mvp:meta [-- --quick] [--seed N]
//
// 1. Breaker search: for every unit, a hill climb over whole teams of 5 that
//    contain it (members and order), scored against a gauntlet of teams. Units
//    play awoken at 3 copies, the shape a round-12 line has.
// 2. Equilibrium: every breaker team plays every other on both sides; the
//    symmetric zero-sum game's mixed equilibrium (multiplicative weights) is
//    the meta. Healthy: ≥5 teams in it, the largest share ≤40%, and every top
//    team beaten reliably (≥60%) by ≥3 others.
//
// The simulation is src/mvp/meta.ts; this script writes its report. Every
// fight goes through fightLines (src/mvp/fight.ts), as the game's do.
// --seed N reruns the whole search from another seed (default 0x5eed), to
// check the verdict isn't one seed's luck.
//
// Writes docs/mvp/meta-health.md and .json (.quick with --quick, .seed-N with
// a seed other than the default).

import { mkdirSync, writeFileSync } from "node:fs";
import type { MvpContent } from "../src/mvp/contract.js";
import { DEFAULT_SEED, META_FULL, META_QUICK, RELIABLE, metaHealth, type Team } from "../src/mvp/meta.js";
import { mvpContent } from "../server/src/mvp/content.js";

const QUICK = process.argv.includes("--quick");
function seedArg(): number {
  const i = process.argv.findIndex((a) => a === "--seed" || a.startsWith("--seed="));
  if (i < 0) return DEFAULT_SEED;
  const raw = process.argv[i]!.includes("=") ? process.argv[i]!.split("=")[1] : process.argv[i + 1];
  const n = Number(raw);
  if (raw === undefined || raw === "" || !Number.isInteger(n)) throw new Error(`--seed needs an integer, got ${raw}`);
  return n;
}
const SEED = seedArg();
const S = QUICK ? META_QUICK : META_FULL;
const { copies: COPIES, gauntlet: GAUNTLET, searchSeeds: SEARCH_SEEDS, searchSteps: SEARCH_STEPS, matrixSeeds: MATRIX_SEEDS, counterRounds: COUNTER_ROUNDS, counterRestarts: COUNTER_RESTARTS } = S;

const content: MvpContent = mvpContent();
const units = content.units;
const byId = new Map(units.map((u) => [u.id, u]));

const t0 = Date.now();
const name = (id: string) => `${byId.get(id)!.emoji} ${byId.get(id)!.name}`;
const teamText = (t: Team) => t.map(name).join(" · ");

const r = metaHealth(content, SEED, S, (line) => console.error(line));
const { found, teams, eq, counters, top, largest, beatenBy, unitShare, fieldScore, fieldOf, checks, healthy } = r;
const { battles, capped } = r.sim.stats;
const capRate = capped / battles;

const report = {
  contentVersion: content.version,
  units: units.length,
  quick: QUICK,
  seed: SEED,
  setup: { copies: COPIES, gauntlet: GAUNTLET, searchSeeds: SEARCH_SEEDS, searchSteps: SEARCH_STEPS, matrixSeeds: MATRIX_SEEDS, counterRounds: COUNTER_ROUNDS, counterRestarts: COUNTER_RESTARTS, candidateTeams: teams.length, countersFound: counters },
  battles,
  chainCappedRate: +capRate.toFixed(4),
  seconds: Math.round((Date.now() - t0) / 1000),
  healthy,
  checks,
  equilibrium: top.map((i) => ({ share: +eq[i]!.toFixed(3), team: teams[i], fieldScore: +fieldScore[i]!.toFixed(3), beatenReliablyBy: beatenBy(i).length })),
  breakers: found.map((f) => ({ unit: f.unit, team: f.team, gauntletScore: +f.score.toFixed(3), fieldScore: +fieldOf(f.team).toFixed(3) })),
};

const pct = (x: number) => `${(x * 100).toFixed(0)}%`;
const md: string[] = [
  "# MVP meta-health report",
  "",
  `Generated by \`npm run mvp:meta${QUICK ? " -- --quick" : ""}${SEED !== DEFAULT_SEED ? ` -- --seed ${SEED}` : ""}\` (scripts/meta-health.ts). Content \`${content.version}\`, ${units.length} units, awoken at ${COPIES} copies, seed ${SEED}.`,
  "",
  `**${healthy ? "Healthy" : "Not healthy"}.**`,
  "",
  "| Check | Rule | Value | |",
  "|---|---|---|---|",
  ...Object.values(checks).map((c) => `| ${c.rule === checks.teamsInEquilibrium.rule ? "Teams in the equilibrium" : c.rule === checks.largestShare.rule ? "Largest share" : "Top teams have answers"} | ${c.rule} | ${typeof c.value === "number" && c.value < 1 && c.value > 0 ? pct(c.value) : c.value} | ${c.pass ? "✅" : "❌"} |`),
  "",
  `${battles.toLocaleString("en")} battles in ${report.seconds}s; ${(capRate * 100).toFixed(2)}% of them hit the chain cap.`,
  "",
  "## The equilibrium",
  "",
  `Mixed equilibrium of ${teams.length} candidate teams playing each other (both sides, ${MATRIX_SEEDS} seeds each): the ${found.length} breaker teams plus ${counters} counters found by ${COUNTER_ROUNDS} rounds of counter search against the equilibrium's teams. Field score = mean score against every candidate team.`,
  "",
  "| Share | Team (front first) | Field score | Beaten ≥60% by |",
  "|---|---|---|---|",
  ...top.map((i) => `| ${pct(eq[i]!)} | ${teamText(teams[i]!)} | ${pct(fieldScore[i]!)} | ${beatenBy(i).length} |`),
  "",
  "## Units in the meta",
  "",
  [...unitShare.entries()].sort((a, b) => b[1] - a[1]).map(([id, s]) => `${name(id)} ${pct(s)}`).join(" · "),
  "",
  "## Breaker search: the best team found for each unit",
  "",
  `Hill climb over members and order (${SEARCH_STEPS} steps), scored against a gauntlet of ${GAUNTLET} teams that fills with earlier breakers. Field score = the team's mean score against every candidate team: the unit's strength at its best, used to tune numbers.`,
  "",
  "| Unit | Tier | Best team | Field score | Gauntlet score |",
  "|---|---|---|---|---|",
  ...[...found].sort((a, b) => fieldOf(b.team) - fieldOf(a.team)).map((f) => `| ${name(f.unit)} | ${byId.get(f.unit)!.tier} | ${teamText(f.team)} | ${pct(fieldOf(f.team))} | ${pct(f.score)} |`),
  "",
];

mkdirSync("docs/mvp", { recursive: true });
const out = `docs/mvp/meta-health${QUICK ? ".quick" : ""}${SEED !== DEFAULT_SEED ? `.seed-${SEED}` : ""}`;
writeFileSync(`${out}.md`, md.join("\n"));
writeFileSync(`${out}.json`, JSON.stringify(report, null, 2) + "\n");
console.log(`${healthy ? "HEALTHY" : "NOT HEALTHY"}: ${top.length} teams, largest ${pct(largest)}, min answers ${checks.topTeamsBeaten.value}, cap ${(capRate * 100).toFixed(2)}%, ${battles} battles, ${report.seconds}s → ${out}.md`);
