#!/usr/bin/env node
import { chromium } from 'playwright';
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
const root=dirname(fileURLToPath(import.meta.url)), repo=join(root,'../..'), html=join(root,'gallery.html'), captures=join(root,'captures');mkdirSync(captures,{recursive:true});
const out=[],log=s=>{console.log(s);out.push(s)},fail=(scope,msg)=>{throw Error(`[${scope}] ${msg}`)},rgb=(hex)=>{const n=parseInt(hex.slice(1),16);return `rgb(${n>>16}, ${(n>>8)&255}, ${n&255})`};
const source=readFileSync(html,'utf8');
try{
log('=== AOI-S22 PASS 4 STRUCTURE / TRUTH ===');
for(const text of ['Field Lens','Split Brief','Causal Atlas','Trigger','Selector','Effect','Ability · Frostbite','Status · Shield','Summon · Imp','Base','Awakened','Fused A+B','No runtime statuses','Summon unavailable','Reference failed','Maks selects / hybridizes / rejects'])if(!source.includes(text))fail('source',`missing ${text}`);
for(const text of ["--pwr:#ffc76a","--pwr-off:#e2c980","--hp:#ff7d72","Frostbiter + Venomancer","pwr:3,hp:17","Imp','A summoned Strike-family Unit with 1 PWR / 2 HP","effect:'Strike — heal 0 (inert basic action)'","absorb the damage up to its stacks, consuming what it absorbs"])if(!source.includes(text))fail('truth',`missing ${text}`);
if(/<(script|link)[^>]+(src|href)=["']https?:/i.test(source))fail('self-contained','external runtime dependency');
const candidate=JSON.parse(readFileSync(join(repo,'candidates/frostbite-striker.json'),'utf8')),frost=candidate.units.find(x=>x.name==='Frostbiter'),stress=readFileSync(join(repo,'src/content/stress.ts'),'utf8'),run=readFileSync(join(repo,'src/run.ts'),'utf8');
if(frost.base.pwr!==2||frost.base.hp!==11||frost.statuses[0].status!=='Shield'||frost.statuses[0].stacks!==3)fail('truth','Frostbiter source drift');
for(const seam of ['Apply 3 Poison, then 1 Curse','export const Imp: UnitDef = { name: "Imp", base: { hp: 2, pwr: 1 }','export const Venomancer: UnitDef = { name: "Venomancer", base: { hp: 6, pwr: 1 }'])if(!(source+stress).includes(seam))fail('truth',`source seam ${seam}`);
if(!run.includes('first.base.hp + second.base.hp')||!run.includes('first.base.pwr + second.base.pwr'))fail('truth','fusion is not additive');
log('structure/truth: PASS exactly three named stances; accepted tokens; truthful Unit/Ability/Status/Summon and additive A+B seams; no external runtime');
const browser=await chromium.launch({headless:true});
try{
 const stances=['lens','brief','atlas'], views=[{name:'desktop',w:1440,h:1000},{name:'phone',w:390,h:844}];
 for(const stance of stances)for(const view of views){
  const page=await browser.newPage({viewport:{width:view.w,height:view.h},reducedMotion:'reduce'});await page.goto(`${pathToFileURL(html).href}?stance=${stance}`);
  const result=await page.evaluate(({stance,w})=>{const visible=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.visibility!=='hidden'&&s.display!=='none'},q=s=>[...document.querySelectorAll(s)],box=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom,w:r.width,h:r.height}};const detail=document.querySelector('.detail'),db=box(detail),cards=q('.unit-button').map(box),targets=q('button').filter(visible).map(e=>({text:e.textContent.trim(),...box(e),outline:getComputedStyle(e).outlineWidth}));const small=q('.detail *').filter(e=>visible(e)&&e.children.length===0&&e.textContent.trim()).map(e=>({text:e.textContent.trim(),font:parseFloat(getComputedStyle(e).fontSize),line:parseFloat(getComputedStyle(e).lineHeight)||0,sw:e.scrollWidth,cw:e.clientWidth,sh:e.scrollHeight,ch:e.clientHeight,intentional:e.closest('.long-copy')!==null}));const statEscapes=q('.unit .stat').filter(e=>{const a=box(e),b=box(e.parentElement);return a.x<b.x-1||a.right>b.right+1||a.y<b.y-1||a.bottom>b.bottom+1}).map(e=>e.textContent.trim());return{stance:document.body.dataset.stance,scrollW:document.documentElement.scrollWidth,offers:q('.unit-button').length,refs:q('[data-ref]').length,proof:q('.proof').length,comparison:visible(document.querySelector('.comparison')),detail:{...db,pos:getComputedStyle(detail).position,modal:detail.getAttribute('aria-modal')},cards,targets,small,statEscapes,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,pwr:getComputedStyle(document.querySelector('.pwr')).color,hp:getComputedStyle(document.querySelector('.hp')).color,activeThesis:q('.thesis .active').length};},{stance,w:view.w});
  if(result.stance!==stance||result.scrollW>view.w)fail(`${stance}/${view.name}`,`stance or page overflow ${JSON.stringify(result)}`);
  if(result.offers!==3||result.refs!==3||result.proof!==4||!result.comparison)fail(`${stance}/${view.name}`,'required visible structure');
  if(result.pwr!==rgb('#ffc76a')||result.hp!==rgb('#ff7d72'))fail(`${stance}/${view.name}`,`stat semantics ${result.pwr}/${result.hp}`);
  if(!result.reduced)fail(`${stance}/${view.name}`,'reduced-motion media did not match');
  if(result.targets.some(x=>x.w<40||x.h<40))fail(`${stance}/${view.name}`,`target floor ${JSON.stringify(result.targets.filter(x=>x.w<40||x.h<40).slice(0,3))}`);
  const clipped=result.small.filter(x=>!x.intentional&&(x.sw>x.cw+3||x.sh>x.ch+3));if(clipped.length)fail(`${stance}/${view.name}`,`unapproved text clipping ${JSON.stringify(clipped.slice(0,3))}`);
  if(result.small.some(x=>x.font<10))fail(`${stance}/${view.name}`,'text below 10px floor');if(result.statEscapes.length)fail(`${stance}/${view.name}`,`stat escaped footer ${result.statEscapes.join(', ')}`);
  if(view.name==='phone'){
   if(result.detail.pos!=='fixed'||Math.abs(result.detail.bottom-view.h)>1||result.detail.modal!=='false')fail(`${stance}/phone`,'bottom-sheet geometry/initial modality');
   const visibleCard=result.cards.some(x=>Math.min(x.bottom,result.detail.y)-Math.max(x.y,0)>=80);if(!visibleCard)fail(`${stance}/phone`,'sheet leaves less than 80px of every alternative visible');
  }else{
   const expected={lens:'absolute',brief:'sticky',atlas:'static'}[stance];if(result.detail.pos!==expected)fail(`${stance}/desktop`,`detail stance ${result.detail.pos} != ${expected}`);
   if(result.cards.some(x=>x.right>result.detail.x&&x.x<result.detail.right&&x.bottom>result.detail.y&&x.y<result.detail.bottom))fail(`${stance}/desktop`,'detail obscures an alternative');
   if(result.activeThesis!==1)fail(`${stance}/desktop`,'active stance explanation');
  }
  for(let i=0;i<await page.locator('button:visible:not([disabled])').count();i++){const b=page.locator('button:visible:not([disabled])').nth(i);await b.focus();const ok=await b.evaluate(e=>document.activeElement===e&&parseFloat(getComputedStyle(e).outlineWidth)>=3);if(!ok)fail(`${stance}/${view.name}`,`focus indicator ${await b.innerText()}`)}
  await page.evaluate(()=>{scrollTo(0,0);document.querySelector('.detail').scrollTop=0;document.activeElement?.blur()});await page.screenshot({path:join(captures,`${stance}-${view.name}.png`),fullPage:view.name==='desktop'});if(view.name==='phone'){await page.locator('.detail').evaluate(e=>e.scrollTop=e.scrollHeight);await page.screenshot({path:join(captures,`${stance}-phone-reference.png`)})}await page.close();log(`${stance}/${view.name}: PASS alternatives + consequences visible; detail stance; no page/text clipping; >=40px targets; >=10px text; 3px focus; reduced motion`);
 }
 const phone=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});await phone.goto(`${pathToFileURL(html).href}?stance=lens`);await phone.locator('.close').click();const opener=phone.locator('.unit-button').nth(1);await opener.focus();await phone.keyboard.press('Enter');if(await phone.locator('#detail-title').innerText()!=='Frostbiter'||!(await phone.locator('.effect span').innerText()).includes('3 Poison'))fail('interaction','selected alternative did not update consequence');if(!await phone.locator('.close').evaluate(e=>document.activeElement===e))fail('interaction','sheet does not focus close first');await phone.keyboard.press('Shift+Tab');if(!await phone.locator('.proof.error button').evaluate(e=>document.activeElement===e))fail('interaction','reverse focus trap');await phone.keyboard.press('Tab');if(!await phone.locator('.close').evaluate(e=>document.activeElement===e))fail('interaction','forward focus trap');await phone.keyboard.press('Escape');if(!await opener.evaluate(e=>document.activeElement===e)||await phone.locator('.detail').isVisible())fail('interaction','Escape close/focus return');await opener.press('Enter');await phone.locator('[data-mode=detail]').click();if(await phone.locator('.comparison').isVisible())fail('interaction','comparison mode toggle');await phone.locator('[data-mode=compare]').click();if(!await phone.locator('.comparison').isVisible())fail('interaction','comparison restore');await phone.locator('[data-ref=status]').click();if(!(await phone.locator('.reference-body').innerText()).includes('Interceptor'))fail('interaction','reference tab');await phone.close();
 log('interaction: PASS keyboard selection updates detail/consequence; close-first order; forward/reverse sheet focus trap; Escape/close return; comparison mode; reference tabs');
}finally{await browser.close()}
const allowed='design/aoi-s22-pass-4/';const status=execFileSync('git',['status','--porcelain','--untracked-files=all'],{cwd:repo,encoding:'utf8'}).trim().split('\n').filter(Boolean).map(x=>x.slice(3));const bad=status.filter(x=>!x.startsWith(allowed)&&!x.startsWith('.pi-subagents/'));if(bad.length)fail('isolation',`non-artifact paths ${bad.join(', ')}`);log(`production isolation: PASS working paths bounded to ${allowed} (subagent runtime artifacts excluded and removed before commit)`);
const files=readdirSync(captures).filter(x=>x.endsWith('.png')).sort(),manifest=files.map(f=>{const p=join(captures,f),buf=readFileSync(p);return `${f}\t${statSync(p).size} bytes\tsha256 ${createHash('sha256').update(buf).digest('hex')}`}).join('\n')+'\n';writeFileSync(join(root,'capture-manifest.txt'),manifest);if(files.length!==9)fail('captures',`expected 9 PNGs, found ${files.length}`);log(`captures: PASS ${files.length} deterministic PNGs (three desktop + three 390px sheet-top + three 390px reference-state)`);log('DESIGN QUALITY: UNJUDGED BY MACHINE — screenshot inspection, fresh independent verifier, then Maks taste gate required.');
}catch(e){log(`FAIL ${e.stack||e}`);process.exitCode=1}finally{writeFileSync(join(root,'check-output.txt'),out.join('\n')+'\n')}
